데이터 전처리(결측값, 이상값)
EDA
Feature Engineering
Feature Selection
데이터 분할
k-fold 교차검증, gridsearch, randomsearch, 데이터증폭pipeline 이용해서 모델 3가지로 비교 분석

trans_date_trans_time (object): 거래가 발생한 날짜 및 시간
cc_num (int64): 사용된 신용카드 번호를 나타내는 숫자
merchant (object): 상점명 또는 거래가 발생한 가맹점의 이름
category (object): 거래가 발생한 상품 또는 서비스의 범주
amt (float64): 해당 거래의 거래 금액
first (object): 카드 소유자의 **이름.
last (object): 카드 소유자의 성.
gender (object): 카드 소유자의 성별
street (object): 카드 소유자의 거주지 주소의 거리
city (object): 카드 소유자의 거주지 도시.
state (object): 카드 소유자의 거주지 주(State).
zip (int64): 카드 소유자의 거주지 우편번호. --> 위도 경도가 있으므로 도시 주 우편번호 삭제
lat (float64): 카드 소유자의 거주지 위도(latitude)
long (float64): 카드 소유자의 거주지 경도(longitude)
city_pop (int64): 카드 소유자가 거주하는 도시의 인구 수
job (object): 카드 소유자의 직업
dob (object): 카드 소유자의 출생일(Date of Birth) ->나이 대체 가능
trans_num (object): 각 거래에 할당된 고유 거래 번호.
unix_time (int64): 거래가 발생한 시간을 유닉스 타임스탬프 형식으로 나타낸 값. -> 첫번째랑 겹침
merch_lat (float64): 가맹점의 위도(latitude) 거래가 발생한 상점의 위치 정보
merch_long (float64): 가맹점의 경도(longitude)
is_fraud (int64): 거래가 사기(fraud)여부를 나타내는 열입니다. 1은 사기, 0은 정상 거래

"first" "last" "street" "city" "state" "zip" "trans_num" "unix_time"

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import koreanize_matplotlib

In [2]:
data = pd.read_csv("./data/creaditcard_fraud_data.csv")
data

,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,Moravian Falls,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,Orient,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,Malad City,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,Boulder,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,Doe Hill,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1852389,2020-12-31 23:59:07,30560609640617,fraud_Reilly and Sons,health_fitness,43.77,Michael,Olson,M,558 Michael Estates,Luray,...,40.4931,-91.8912,519,Town planner,1966-02-13,9b1f753c79894c9f4b71f04581835ada,1388534347,39.946837,-91.333331,0
1852390,2020-12-31 23:59:09,3556613125071656,fraud_Hoppe-Parisian,kids_pets,111.84,Jose,Vasquez,M,572 Davis Mountains,Lake Jackson,...,29.0393,-95.4401,28739,Futures trader,1999-12-27,2090647dac2c89a1d86c514c427f5b91,1388534349,29.661049,-96.186633,0
1852391,2020-12-31 23:59:15,6011724471098086,fraud_Rau-Robel,kids_pets,86.88,Ann,Lawson,F,144 Evans Islands Apt. 683,Burbank,...,46.1966,-118.9017,3684,Musician,1981-11-29,6c5b7c8add471975aa0fec023b2e8408,1388534355,46.658340,-119.715054,0
1852392,2020-12-31 23:59:24,4079773899158,fraud_Breitenberg LLC,travel,7.99,Eric,Preston,M,7020 Doyle Stream Apt. 951,Mesa,...,44.6255,-116.4493,129,Cartographer,1965-12-15,14392d723bb7737606b2700ac791b7aa,1388534364,44.470525,-117.080888,0
1852393,2020-12-31 23:59:34,4170689372027579,fraud_Dare-Marvin,entertainment,38.13,Samuel,Frey,M,830 Myers Plaza Apt. 384,Edmond,...,35.6665,-97.4798,116001,Media buyer,1993-05-10,1765bb45b3aa3224b4cdcb6e7a96cee3,1388534374,36.210097,-97.036372,0

In [3]:
pd.options.display.float_format = '{:.6f}'.format

In [4]:
data.describe()

,cc_num,amt,zip,lat,long,city_pop,unix_time,merch_lat,merch_long,is_fraud
count,1852394.000000,1852394.000000,1852394.000000,1852394.000000,1852394.000000,1852394.000000,1852394.000000,1852394.000000,1852394.000000,1852394.000000
mean,417386038393710400.000000,70.063567,48813.258191,38.539311,-90.227832,88643.674509,1358674218.834364,38.538976,-90.227940,0.005210
std,1309115265318734848.000000,159.253975,26881.845966,5.071470,13.747895,301487.618344,18195081.387560,5.105604,13.759692,0.071992
min,60416207185.000000,1.000000,1257.000000,20.027100,-165.672300,23.000000,1325376018.000000,19.027422,-166.671575,0.000000
25%,180042946491150.000000,9.640000,26237.000000,34.668900,-96.798000,741.000000,1343016823.750000,34.740122,-96.899440,0.000000
50%,3521417320836166.000000,47.450000,48174.000000,39.354300,-87.476900,2443.000000,1357089331.000000,39.368900,-87.440694,0.000000
75%,4642255475285942.000000,83.100000,72042.000000,41.940400,-80.158000,20328.000000,1374581485.250000,41.956263,-80.245108,0.000000
max,4992346398065154048.000000,28948.900000,99921.000000,66.693300,-67.950300,2906700.000000,1388534374.000000,67.510267,-66.950902,1.000000

In [5]:
data = data.drop(["first", "last", "street", "city", "state", "zip", "trans_num", "unix_time"], axis=1)

In [6]:
data

,trans_date_trans_time,cc_num,merchant,category,amt,gender,lat,long,city_pop,job,dob,merch_lat,merch_long,is_fraud
0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.970000,F,36.078800,-81.178100,3495,"Psychologist, counselling",1988-03-09,36.011293,-82.048315,0
1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.230000,F,48.887800,-118.210500,149,Special educational needs teacher,1978-06-21,49.159047,-118.186462,0
2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.110000,M,42.180800,-112.262000,4154,Nature conservation officer,1962-01-19,43.150704,-112.154481,0
3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.000000,M,46.230600,-112.113800,1939,Patent attorney,1967-01-12,47.034331,-112.561071,0
4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.960000,M,38.420700,-79.462900,99,Dance movement psychotherapist,1986-03-28,38.674999,-78.632459,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1852389,2020-12-31 23:59:07,30560609640617,fraud_Reilly and Sons,health_fitness,43.770000,M,40.493100,-91.891200,519,Town planner,1966-02-13,39.946837,-91.333331,0
1852390,2020-12-31 23:59:09,3556613125071656,fraud_Hoppe-Parisian,kids_pets,111.840000,M,29.039300,-95.440100,28739,Futures trader,1999-12-27,29.661049,-96.186633,0
1852391,2020-12-31 23:59:15,6011724471098086,fraud_Rau-Robel,kids_pets,86.880000,F,46.196600,-118.901700,3684,Musician,1981-11-29,46.658340,-119.715054,0
1852392,2020-12-31 23:59:24,4079773899158,fraud_Breitenberg LLC,travel,7.990000,M,44.625500,-116.449300,129,Cartographer,1965-12-15,44.470525,-117.080888,0
1852393,2020-12-31 23:59:34,4170689372027579,fraud_Dare-Marvin,entertainment,38.130000,M,35.666500,-97.479800,116001,Media buyer,1993-05-10,36.210097,-97.036372,0

In [7]:
# 데이터가 많으므로 train과 test로 나눠서 작업

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
train, test = train_test_split(data, stratify=data['is_fraud'], test_size=0.4, random_state=10)

In [10]:
train['is_fraud'].value_counts()

is_fraud
0    1105645
1       5791
Name: count, dtype: int64

In [11]:
test['is_fraud'].value_counts()

is_fraud
0    737098
1      3860
Name: count, dtype: int64

In [12]:
# train으로 전처리

In [13]:
train

,trans_date_trans_time,cc_num,merchant,category,amt,gender,lat,long,city_pop,job,dob,merch_lat,merch_long,is_fraud
1349054,2020-07-09 06:53:00,377895991033232,fraud_Zboncak Ltd,food_dining,130.680000,F,41.468200,-72.575100,5438,"Librarian, academic",1964-11-17,41.809910,-73.494581,0
508153,2019-08-08 18:20:52,38588538868506,fraud_Fritsch and Sons,health_fitness,54.460000,F,30.188600,-103.221400,498,Lexicographer,1990-11-23,30.858585,-102.458928,0
912706,2019-12-29 14:00:23,349612764943496,fraud_Windler LLC,kids_pets,42.420000,M,37.104600,-83.570600,467,"Psychologist, forensic",1984-06-04,36.405837,-84.030634,0
530344,2019-08-16 18:02:28,4874017206859125,"fraud_Prosacco, Kreiger and Kovacek",home,77.050000,F,45.409300,-122.684700,42817,Planning and development surveyor,1982-05-28,46.111612,-121.729974,0
1126761,2020-04-14 00:21:46,5501083170975659,fraud_Jast Ltd,shopping_net,1.950000,M,41.146400,-81.510700,47772,Equities trader,1966-01-04,40.945120,-82.361809,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1365820,2020-07-14 19:29:36,676369110710,fraud_Nienow PLC,entertainment,11.330000,M,42.496900,-83.291100,75830,"Engineer, automotive",1974-12-28,41.566847,-84.015768,0
105708,2019-03-02 15:25:33,30238755902988,fraud_Macejkovic-Lesch,shopping_pos,4.870000,F,30.592000,-97.289300,1766,Press sub,1976-01-02,30.892429,-97.713717,0
602068,2019-09-13 03:44:55,4099707841315751,fraud_Hackett-Lueilwitz,grocery_pos,70.320000,M,38.258600,-78.407400,9815,"Designer, ceramics/pottery",1975-07-07,38.195483,-78.668541,0
1780135,2020-12-15 16:09:57,345933964507467,"fraud_Wuckert, Wintheiser and Friesen",home,121.300000,F,38.412100,-75.281100,718,Regulatory affairs officer,1985-03-19,38.001255,-76.190657,0
1489600,2020-08-28 03:24:55,4158008602445,fraud_Huels-Hahn,gas_transport,59.210000,F,44.527400,-93.019600,1201,Barrister,1979-12-27,44.272907,-93.548241,0

In [14]:
train['cc_num'].nunique() #카드번호 중복데이터 체크(한 카드로 여러변 결제된 건이 999개)

999

In [15]:
#data['name']을 ["first", "last"]로 생성해서 중복 체크하니 989개, 동명이인이 있다는 의미

# 카드 번호에 따른 평균 지출 금액과 표준편차

In [16]:
train.groupby('cc_num')['amt'].agg(['mean', 'std'])

                          mean         std
cc_num
60416207185          61.313763  161.657736
60422928733          65.278174   90.900398
60423098130         116.621949 1248.438561
60427851591         104.790490  119.746806
60487002085          70.822757  182.542688
...                        ...         ...
4958589671582726883  68.121702  156.519908
4973530368125489546  69.837241  136.312982
4980323467523543940  71.559318  126.591056
4989847570577635369  93.801177  136.023783
4992346398065154184  66.115361  113.064205

[999 rows x 2 columns]

In [17]:
train.groupby('cc_num')['amt'].agg(['mean', 'std']).reset_index() #인덱스로 넣기

                  cc_num       mean         std
0            60416207185  61.313763  161.657736
1            60422928733  65.278174   90.900398
2            60423098130 116.621949 1248.438561
3            60427851591 104.790490  119.746806
4            60487002085  70.822757  182.542688
..                   ...        ...         ...
994  4958589671582726883  68.121702  156.519908
995  4973530368125489546  69.837241  136.312982
996  4980323467523543940  71.559318  126.591056
997  4989847570577635369  93.801177  136.023783
998  4992346398065154184  66.115361  113.064205

[999 rows x 3 columns]

In [18]:
amt_by_cc_num = train.groupby('cc_num')['amt'].agg(['mean', 'std']).reset_index()

In [19]:
amt_by_cc_num

                  cc_num       mean         std
0            60416207185  61.313763  161.657736
1            60422928733  65.278174   90.900398
2            60423098130 116.621949 1248.438561
3            60427851591 104.790490  119.746806
4            60487002085  70.822757  182.542688
..                   ...        ...         ...
994  4958589671582726883  68.121702  156.519908
995  4973530368125489546  69.837241  136.312982
996  4980323467523543940  71.559318  126.591056
997  4989847570577635369  93.801177  136.023783
998  4992346398065154184  66.115361  113.064205

[999 rows x 3 columns]

In [20]:
#train, amtamt_by_cc_num을 합치는데, cc_num을 기준으로 mean과 std 대입하도록
train = pd.merge(train, amt_by_cc_num, how='left', on='cc_num')
train

,trans_date_trans_time,cc_num,merchant,category,amt,gender,lat,long,city_pop,job,dob,merch_lat,merch_long,is_fraud,mean,std
0,2020-07-09 06:53:00,377895991033232,fraud_Zboncak Ltd,food_dining,130.680000,F,41.468200,-72.575100,5438,"Librarian, academic",1964-11-17,41.809910,-73.494581,0,73.414795,131.574335
1,2019-08-08 18:20:52,38588538868506,fraud_Fritsch and Sons,health_fitness,54.460000,F,30.188600,-103.221400,498,Lexicographer,1990-11-23,30.858585,-102.458928,0,59.766495,147.773396
2,2019-12-29 14:00:23,349612764943496,fraud_Windler LLC,kids_pets,42.420000,M,37.104600,-83.570600,467,"Psychologist, forensic",1984-06-04,36.405837,-84.030634,0,97.885517,103.125597
3,2019-08-16 18:02:28,4874017206859125,"fraud_Prosacco, Kreiger and Kovacek",home,77.050000,F,45.409300,-122.684700,42817,Planning and development surveyor,1982-05-28,46.111612,-121.729974,0,89.205841,127.017879
4,2020-04-14 00:21:46,5501083170975659,fraud_Jast Ltd,shopping_net,1.950000,M,41.146400,-81.510700,47772,Equities trader,1966-01-04,40.945120,-82.361809,0,63.371306,112.601803
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1111431,2020-07-14 19:29:36,676369110710,fraud_Nienow PLC,entertainment,11.330000,M,42.496900,-83.291100,75830,"Engineer, automotive",1974-12-28,41.566847,-84.015768,0,59.117192,149.629935
1111432,2019-03-02 15:25:33,30238755902988,fraud_Macejkovic-Lesch,shopping_pos,4.870000,F,30.592000,-97.289300,1766,Press sub,1976-01-02,30.892429,-97.713717,0,54.625542,131.268419
1111433,2019-09-13 03:44:55,4099707841315751,fraud_Hackett-Lueilwitz,grocery_pos,70.320000,M,38.258600,-78.407400,9815,"Designer, ceramics/pottery",1975-07-07,38.195483,-78.668541,0,62.540364,293.792067
1111434,2020-12-15 16:09:57,345933964507467,"fraud_Wuckert, Wintheiser and Friesen",home,121.300000,F,38.412100,-75.281100,718,Regulatory affairs officer,1985-03-19,38.001255,-76.190657,0,55.467010,99.480757
1111435,2020-08-28 03:24:55,4158008602445,fraud_Huels-Hahn,gas_transport,59.210000,F,44.527400,-93.019600,1201,Barrister,1979-12-27,44.272907,-93.548241,0,53.571404,100.104338

# 이상지출 탐지하기
* 평소 사용자가 지출하던 금액보다 과도하게 높은 경우
* z-score 이용해 탐지 (표준편차를 구해서 z스코어 3정도 떨어진 경우 ~ 극단값 구함)
* z-score = 값 - 평균 / 표준편차

In [21]:
train['amt_z_scroe'] = (train['amt'] - train['mean']) / train['std']

In [22]:
train

,trans_date_trans_time,cc_num,merchant,category,amt,gender,lat,long,city_pop,job,dob,merch_lat,merch_long,is_fraud,mean,std,amt_z_scroe
0,2020-07-09 06:53:00,377895991033232,fraud_Zboncak Ltd,food_dining,130.680000,F,41.468200,-72.575100,5438,"Librarian, academic",1964-11-17,41.809910,-73.494581,0,73.414795,131.574335,0.435231
1,2019-08-08 18:20:52,38588538868506,fraud_Fritsch and Sons,health_fitness,54.460000,F,30.188600,-103.221400,498,Lexicographer,1990-11-23,30.858585,-102.458928,0,59.766495,147.773396,-0.035910
2,2019-12-29 14:00:23,349612764943496,fraud_Windler LLC,kids_pets,42.420000,M,37.104600,-83.570600,467,"Psychologist, forensic",1984-06-04,36.405837,-84.030634,0,97.885517,103.125597,-0.537844
3,2019-08-16 18:02:28,4874017206859125,"fraud_Prosacco, Kreiger and Kovacek",home,77.050000,F,45.409300,-122.684700,42817,Planning and development surveyor,1982-05-28,46.111612,-121.729974,0,89.205841,127.017879,-0.095702
4,2020-04-14 00:21:46,5501083170975659,fraud_Jast Ltd,shopping_net,1.950000,M,41.146400,-81.510700,47772,Equities trader,1966-01-04,40.945120,-82.361809,0,63.371306,112.601803,-0.545474
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1111431,2020-07-14 19:29:36,676369110710,fraud_Nienow PLC,entertainment,11.330000,M,42.496900,-83.291100,75830,"Engineer, automotive",1974-12-28,41.566847,-84.015768,0,59.117192,149.629935,-0.319369
1111432,2019-03-02 15:25:33,30238755902988,fraud_Macejkovic-Lesch,shopping_pos,4.870000,F,30.592000,-97.289300,1766,Press sub,1976-01-02,30.892429,-97.713717,0,54.625542,131.268419,-0.379037
1111433,2019-09-13 03:44:55,4099707841315751,fraud_Hackett-Lueilwitz,grocery_pos,70.320000,M,38.258600,-78.407400,9815,"Designer, ceramics/pottery",1975-07-07,38.195483,-78.668541,0,62.540364,293.792067,0.026480
1111434,2020-12-15 16:09:57,345933964507467,"fraud_Wuckert, Wintheiser and Friesen",home,121.300000,F,38.412100,-75.281100,718,Regulatory affairs officer,1985-03-19,38.001255,-76.190657,0,55.467010,99.480757,0.661766
1111435,2020-08-28 03:24:55,4158008602445,fraud_Huels-Hahn,gas_transport,59.210000,F,44.527400,-93.019600,1201,Barrister,1979-12-27,44.272907,-93.548241,0,53.571404,100.104338,0.056327

In [23]:
amt_z_over_3 = train[train['amt_z_scroe'] > 3]

In [24]:
amt_z_over_3['is_fraud'].value_counts()

is_fraud
0    13587
1     2522
Name: count, dtype: int64

In [25]:
amt_z_over_3['is_fraud'].mean() # 0.16

0.15655844558942206

In [26]:
train['is_fraud'].mean() #0.005

0.005210376485915518

# 이상지출 탐지하기 2
* 사람별로 지

In [27]:
train[train['cc_num'] == 377895991033232]['category'].value_counts()

category
home              94
food_dining       84
grocery_pos       84
shopping_pos      84
entertainment     81
misc_pos          76
gas_transport     76
personal_care     76
kids_pets         72
health_fitness    45
shopping_net      44
travel            36
misc_net          28
grocery_net       21
Name: count, dtype: int64

In [28]:
train['category'].nunique()

14

In [29]:
train[train['cc_num']== 4158008602445]['category'].value_counts()

category
gas_transport     63
personal_care     43
home              42
shopping_pos      42
kids_pets         41
grocery_pos       40
food_dining       36
shopping_net      34
misc_pos          27
misc_net          25
entertainment     21
health_fitness    21
travel            14
grocery_net       14
Name: count, dtype: int64

In [30]:
train.groupby(['cc_num', 'category'])['amt'].agg(['mean', 'std'])

                                        mean        std
cc_num              category
60416207185         entertainment  51.753913  82.038576
                    food_dining    26.269865  37.007297
                    gas_transport  60.279459  16.723792
                    grocery_net    53.136222  19.302610
                    grocery_pos   100.872627  20.693912
...                                      ...        ...
4992346398065154184 misc_pos       62.650132 195.941653
                    personal_care  50.903566  50.919109
                    shopping_net  107.564161 262.102933
                    shopping_pos   61.826306 184.695165
                    travel          8.257385  15.263738

[13061 rows x 2 columns]

In [31]:
amtbycategory=train.groupby(['cc_num','category'])['amt'].agg(['mean','std']).reset_index()
amtbycategory

                    cc_num       category       mean        std
0              60416207185  entertainment  51.753913  82.038576
1              60416207185    food_dining  26.269865  37.007297
2              60416207185  gas_transport  60.279459  16.723792
3              60416207185    grocery_net  53.136222  19.302610
4              60416207185    grocery_pos 100.872627  20.693912
...                    ...            ...        ...        ...
13056  4992346398065154184       misc_pos  62.650132 195.941653
13057  4992346398065154184  personal_care  50.903566  50.919109
13058  4992346398065154184   shopping_net 107.564161 262.102933
13059  4992346398065154184   shopping_pos  61.826306 184.695165
13060  4992346398065154184         travel   8.257385  15.263738

[13061 rows x 4 columns]

In [32]:
train = pd.merge(train, amtbycategory, how='left', on=['cc_num', 'category'], suffixes=('_train', '_amtbycategory'))
train

,trans_date_trans_time,cc_num,merchant,category,amt,gender,lat,long,city_pop,job,dob,merch_lat,merch_long,is_fraud,mean_train,std_train,amt_z_scroe,mean_amtbycategory,std_amtbycategory
0,2020-07-09 06:53:00,377895991033232,fraud_Zboncak Ltd,food_dining,130.680000,F,41.468200,-72.575100,5438,"Librarian, academic",1964-11-17,41.809910,-73.494581,0,73.414795,131.574335,0.435231,77.601548,45.818777
1,2019-08-08 18:20:52,38588538868506,fraud_Fritsch and Sons,health_fitness,54.460000,F,30.188600,-103.221400,498,Lexicographer,1990-11-23,30.858585,-102.458928,0,59.766495,147.773396,-0.035910,47.625806,47.145251
2,2019-12-29 14:00:23,349612764943496,fraud_Windler LLC,kids_pets,42.420000,M,37.104600,-83.570600,467,"Psychologist, forensic",1984-06-04,36.405837,-84.030634,0,97.885517,103.125597,-0.537844,49.757807,4.623726
3,2019-08-16 18:02:28,4874017206859125,"fraud_Prosacco, Kreiger and Kovacek",home,77.050000,F,45.409300,-122.684700,42817,Planning and development surveyor,1982-05-28,46.111612,-121.729974,0,89.205841,127.017879,-0.095702,60.795242,47.326641
4,2020-04-14 00:21:46,5501083170975659,fraud_Jast Ltd,shopping_net,1.950000,M,41.146400,-81.510700,47772,Equities trader,1966-01-04,40.945120,-82.361809,0,63.371306,112.601803,-0.545474,95.786579,209.203479
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1111431,2020-07-14 19:29:36,676369110710,fraud_Nienow PLC,entertainment,11.330000,M,42.496900,-83.291100,75830,"Engineer, automotive",1974-12-28,41.566847,-84.015768,0,59.117192,149.629935,-0.319369,71.607939,91.758240
1111432,2019-03-02 15:25:33,30238755902988,fraud_Macejkovic-Lesch,shopping_pos,4.870000,F,30.592000,-97.289300,1766,Press sub,1976-01-02,30.892429,-97.713717,0,54.625542,131.268419,-0.379037,53.431014,304.858339
1111433,2019-09-13 03:44:55,4099707841315751,fraud_Hackett-Lueilwitz,grocery_pos,70.320000,M,38.258600,-78.407400,9815,"Designer, ceramics/pottery",1975-07-07,38.195483,-78.668541,0,62.540364,293.792067,0.026480,64.247117,34.855381
1111434,2020-12-15 16:09:57,345933964507467,"fraud_Wuckert, Wintheiser and Friesen",home,121.300000,F,38.412100,-75.281100,718,Regulatory affairs officer,1985-03-19,38.001255,-76.190657,0,55.467010,99.480757,0.661766,50.198143,50.149951
1111435,2020-08-28 03:24:55,4158008602445,fraud_Huels-Hahn,gas_transport,59.210000,F,44.527400,-93.019600,1201,Barrister,1979-12-27,44.272907,-93.548241,0,53.571404,100.104338,0.056327,59.730952,13.972844

In [34]:
train['category_z_score']= (train['amt']-train['mean_train'])/ train['std_train']
train

,trans_date_trans_time,cc_num,merchant,category,amt,gender,lat,long,city_pop,job,dob,merch_lat,merch_long,is_fraud,mean_train,std_train,amt_z_scroe,mean_amtbycategory,std_amtbycategory,category_z_score
0,2020-07-09 06:53:00,377895991033232,fraud_Zboncak Ltd,food_dining,130.680000,F,41.468200,-72.575100,5438,"Librarian, academic",1964-11-17,41.809910,-73.494581,0,73.414795,131.574335,0.435231,77.601548,45.818777,0.435231
1,2019-08-08 18:20:52,38588538868506,fraud_Fritsch and Sons,health_fitness,54.460000,F,30.188600,-103.221400,498,Lexicographer,1990-11-23,30.858585,-102.458928,0,59.766495,147.773396,-0.035910,47.625806,47.145251,-0.035910
2,2019-12-29 14:00:23,349612764943496,fraud_Windler LLC,kids_pets,42.420000,M,37.104600,-83.570600,467,"Psychologist, forensic",1984-06-04,36.405837,-84.030634,0,97.885517,103.125597,-0.537844,49.757807,4.623726,-0.537844
3,2019-08-16 18:02:28,4874017206859125,"fraud_Prosacco, Kreiger and Kovacek",home,77.050000,F,45.409300,-122.684700,42817,Planning and development surveyor,1982-05-28,46.111612,-121.729974,0,89.205841,127.017879,-0.095702,60.795242,47.326641,-0.095702
4,2020-04-14 00:21:46,5501083170975659,fraud_Jast Ltd,shopping_net,1.950000,M,41.146400,-81.510700,47772,Equities trader,1966-01-04,40.945120,-82.361809,0,63.371306,112.601803,-0.545474,95.786579,209.203479,-0.545474
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1111431,2020-07-14 19:29:36,676369110710,fraud_Nienow PLC,entertainment,11.330000,M,42.496900,-83.291100,75830,"Engineer, automotive",1974-12-28,41.566847,-84.015768,0,59.117192,149.629935,-0.319369,71.607939,91.758240,-0.319369
1111432,2019-03-02 15:25:33,30238755902988,fraud_Macejkovic-Lesch,shopping_pos,4.870000,F,30.592000,-97.289300,1766,Press sub,1976-01-02,30.892429,-97.713717,0,54.625542,131.268419,-0.379037,53.431014,304.858339,-0.379037
1111433,2019-09-13 03:44:55,4099707841315751,fraud_Hackett-Lueilwitz,grocery_pos,70.320000,M,38.258600,-78.407400,9815,"Designer, ceramics/pottery",1975-07-07,38.195483,-78.668541,0,62.540364,293.792067,0.026480,64.247117,34.855381,0.026480
1111434,2020-12-15 16:09:57,345933964507467,"fraud_Wuckert, Wintheiser and Friesen",home,121.300000,F,38.412100,-75.281100,718,Regulatory affairs officer,1985-03-19,38.001255,-76.190657,0,55.467010,99.480757,0.661766,50.198143,50.149951,0.661766
1111435,2020-08-28 03:24:55,4158008602445,fraud_Huels-Hahn,gas_transport,59.210000,F,44.527400,-93.019600,1201,Barrister,1979-12-27,44.272907,-93.548241,0,53.571404,100.104338,0.056327,59.730952,13.972844,0.056327

In [37]:
train = pd.merge(train, amtbycategory, how = 'left', on=['cc_num', 'category'])
train

,trans_date_trans_time,cc_num,merchant,category,amt,gender,lat,long,city_pop,job,...,mean_train,std_train,amt_z_scroe,mean_amtbycategory,std_amtbycategory,category_z_score,mean_x,std_x,mean_y,std_y
0,2020-07-09 06:53:00,377895991033232,fraud_Zboncak Ltd,food_dining,130.680000,F,41.468200,-72.575100,5438,"Librarian, academic",...,73.414795,131.574335,0.435231,77.601548,45.818777,0.435231,77.601548,45.818777,77.601548,45.818777
1,2019-08-08 18:20:52,38588538868506,fraud_Fritsch and Sons,health_fitness,54.460000,F,30.188600,-103.221400,498,Lexicographer,...,59.766495,147.773396,-0.035910,47.625806,47.145251,-0.035910,47.625806,47.145251,47.625806,47.145251
2,2019-12-29 14:00:23,349612764943496,fraud_Windler LLC,kids_pets,42.420000,M,37.104600,-83.570600,467,"Psychologist, forensic",...,97.885517,103.125597,-0.537844,49.757807,4.623726,-0.537844,49.757807,4.623726,49.757807,4.623726
3,2019-08-16 18:02:28,4874017206859125,"fraud_Prosacco, Kreiger and Kovacek",home,77.050000,F,45.409300,-122.684700,42817,Planning and development surveyor,...,89.205841,127.017879,-0.095702,60.795242,47.326641,-0.095702,60.795242,47.326641,60.795242,47.326641
4,2020-04-14 00:21:46,5501083170975659,fraud_Jast Ltd,shopping_net,1.950000,M,41.146400,-81.510700,47772,Equities trader,...,63.371306,112.601803,-0.545474,95.786579,209.203479,-0.545474,95.786579,209.203479,95.786579,209.203479
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1111431,2020-07-14 19:29:36,676369110710,fraud_Nienow PLC,entertainment,11.330000,M,42.496900,-83.291100,75830,"Engineer, automotive",...,59.117192,149.629935,-0.319369,71.607939,91.758240,-0.319369,71.607939,91.758240,71.607939,91.758240
1111432,2019-03-02 15:25:33,30238755902988,fraud_Macejkovic-Lesch,shopping_pos,4.870000,F,30.592000,-97.289300,1766,Press sub,...,54.625542,131.268419,-0.379037,53.431014,304.858339,-0.379037,53.431014,304.858339,53.431014,304.858339
1111433,2019-09-13 03:44:55,4099707841315751,fraud_Hackett-Lueilwitz,grocery_pos,70.320000,M,38.258600,-78.407400,9815,"Designer, ceramics/pottery",...,62.540364,293.792067,0.026480,64.247117,34.855381,0.026480,64.247117,34.855381,64.247117,34.855381
1111434,2020-12-15 16:09:57,345933964507467,"fraud_Wuckert, Wintheiser and Friesen",home,121.300000,F,38.412100,-75.281100,718,Regulatory affairs officer,...,55.467010,99.480757,0.661766,50.198143,50.149951,0.661766,50.198143,50.149951,50.198143,50.149951
1111435,2020-08-28 03:24:55,4158008602445,fraud_Huels-Hahn,gas_transport,59.210000,F,44.527400,-93.019600,1201,Barrister,...,53.571404,100.104338,0.056327,59.730952,13.972844,0.056327,59.730952,13.972844,59.730952,13.972844

In [39]:
train

,trans_date_trans_time,cc_num,merchant,category,amt,gender,lat,long,city_pop,job,...,mean_train,std_train,amt_z_scroe,mean_amtbycategory,std_amtbycategory,category_z_score,mean_x,std_x,mean_y,std_y
0,2020-07-09 06:53:00,377895991033232,fraud_Zboncak Ltd,food_dining,130.680000,F,41.468200,-72.575100,5438,"Librarian, academic",...,73.414795,131.574335,0.435231,77.601548,45.818777,0.435231,77.601548,45.818777,77.601548,45.818777
1,2019-08-08 18:20:52,38588538868506,fraud_Fritsch and Sons,health_fitness,54.460000,F,30.188600,-103.221400,498,Lexicographer,...,59.766495,147.773396,-0.035910,47.625806,47.145251,-0.035910,47.625806,47.145251,47.625806,47.145251
2,2019-12-29 14:00:23,349612764943496,fraud_Windler LLC,kids_pets,42.420000,M,37.104600,-83.570600,467,"Psychologist, forensic",...,97.885517,103.125597,-0.537844,49.757807,4.623726,-0.537844,49.757807,4.623726,49.757807,4.623726
3,2019-08-16 18:02:28,4874017206859125,"fraud_Prosacco, Kreiger and Kovacek",home,77.050000,F,45.409300,-122.684700,42817,Planning and development surveyor,...,89.205841,127.017879,-0.095702,60.795242,47.326641,-0.095702,60.795242,47.326641,60.795242,47.326641
4,2020-04-14 00:21:46,5501083170975659,fraud_Jast Ltd,shopping_net,1.950000,M,41.146400,-81.510700,47772,Equities trader,...,63.371306,112.601803,-0.545474,95.786579,209.203479,-0.545474,95.786579,209.203479,95.786579,209.203479
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1111431,2020-07-14 19:29:36,676369110710,fraud_Nienow PLC,entertainment,11.330000,M,42.496900,-83.291100,75830,"Engineer, automotive",...,59.117192,149.629935,-0.319369,71.607939,91.758240,-0.319369,71.607939,91.758240,71.607939,91.758240
1111432,2019-03-02 15:25:33,30238755902988,fraud_Macejkovic-Lesch,shopping_pos,4.870000,F,30.592000,-97.289300,1766,Press sub,...,54.625542,131.268419,-0.379037,53.431014,304.858339,-0.379037,53.431014,304.858339,53.431014,304.858339
1111433,2019-09-13 03:44:55,4099707841315751,fraud_Hackett-Lueilwitz,grocery_pos,70.320000,M,38.258600,-78.407400,9815,"Designer, ceramics/pottery",...,62.540364,293.792067,0.026480,64.247117,34.855381,0.026480,64.247117,34.855381,64.247117,34.855381
1111434,2020-12-15 16:09:57,345933964507467,"fraud_Wuckert, Wintheiser and Friesen",home,121.300000,F,38.412100,-75.281100,718,Regulatory affairs officer,...,55.467010,99.480757,0.661766,50.198143,50.149951,0.661766,50.198143,50.149951,50.198143,50.149951
1111435,2020-08-28 03:24:55,4158008602445,fraud_Huels-Hahn,gas_transport,59.210000,F,44.527400,-93.019600,1201,Barrister,...,53.571404,100.104338,0.056327,59.730952,13.972844,0.056327,59.730952,13.972844,59.730952,13.972844

In [42]:
train= train.drop(['mean_x','std_x','mean_y','std_y'], axis = 1)
train

,trans_date_trans_time,cc_num,merchant,category,amt,gender,lat,long,city_pop,job,dob,merch_lat,merch_long,is_fraud,mean_train,std_train,amt_z_scroe,mean_amtbycategory,std_amtbycategory,category_z_score
0,2020-07-09 06:53:00,377895991033232,fraud_Zboncak Ltd,food_dining,130.680000,F,41.468200,-72.575100,5438,"Librarian, academic",1964-11-17,41.809910,-73.494581,0,73.414795,131.574335,0.435231,77.601548,45.818777,0.435231
1,2019-08-08 18:20:52,38588538868506,fraud_Fritsch and Sons,health_fitness,54.460000,F,30.188600,-103.221400,498,Lexicographer,1990-11-23,30.858585,-102.458928,0,59.766495,147.773396,-0.035910,47.625806,47.145251,-0.035910
2,2019-12-29 14:00:23,349612764943496,fraud_Windler LLC,kids_pets,42.420000,M,37.104600,-83.570600,467,"Psychologist, forensic",1984-06-04,36.405837,-84.030634,0,97.885517,103.125597,-0.537844,49.757807,4.623726,-0.537844
3,2019-08-16 18:02:28,4874017206859125,"fraud_Prosacco, Kreiger and Kovacek",home,77.050000,F,45.409300,-122.684700,42817,Planning and development surveyor,1982-05-28,46.111612,-121.729974,0,89.205841,127.017879,-0.095702,60.795242,47.326641,-0.095702
4,2020-04-14 00:21:46,5501083170975659,fraud_Jast Ltd,shopping_net,1.950000,M,41.146400,-81.510700,47772,Equities trader,1966-01-04,40.945120,-82.361809,0,63.371306,112.601803,-0.545474,95.786579,209.203479,-0.545474
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1111431,2020-07-14 19:29:36,676369110710,fraud_Nienow PLC,entertainment,11.330000,M,42.496900,-83.291100,75830,"Engineer, automotive",1974-12-28,41.566847,-84.015768,0,59.117192,149.629935,-0.319369,71.607939,91.758240,-0.319369
1111432,2019-03-02 15:25:33,30238755902988,fraud_Macejkovic-Lesch,shopping_pos,4.870000,F,30.592000,-97.289300,1766,Press sub,1976-01-02,30.892429,-97.713717,0,54.625542,131.268419,-0.379037,53.431014,304.858339,-0.379037
1111433,2019-09-13 03:44:55,4099707841315751,fraud_Hackett-Lueilwitz,grocery_pos,70.320000,M,38.258600,-78.407400,9815,"Designer, ceramics/pottery",1975-07-07,38.195483,-78.668541,0,62.540364,293.792067,0.026480,64.247117,34.855381,0.026480
1111434,2020-12-15 16:09:57,345933964507467,"fraud_Wuckert, Wintheiser and Friesen",home,121.300000,F,38.412100,-75.281100,718,Regulatory affairs officer,1985-03-19,38.001255,-76.190657,0,55.467010,99.480757,0.661766,50.198143,50.149951,0.661766
1111435,2020-08-28 03:24:55,4158008602445,fraud_Huels-Hahn,gas_transport,59.210000,F,44.527400,-93.019600,1201,Barrister,1979-12-27,44.272907,-93.548241,0,53.571404,100.104338,0.056327,59.730952,13.972844,0.056327

In [43]:
train.groupby('is_fraud')['merchant'].value_counts()

is_fraud  merchant
0         fraud_Kilback LLC                   3661
          fraud_Schumm PLC                    3137
          fraud_Cormier LLC                   3064
          fraud_Boyer PLC                     3025
          fraud_Dickinson Ltd                 2961
                                              ...
1         fraud_Wilkinson PLC                    1
          fraud_Will Ltd                         1
          fraud_Wiza, Schaden and Stark          1
          fraud_Yost-Rogahn                      1
          fraud_Zemlak, Tillman and Cremin       1
Name: count, Length: 1352, dtype: int64

In [44]:
happen_fraud = train.groupby(['merchant', 'category'])[['is_fraud']].mean().sort_values(by='is_fraud', ascending=False).reset_index()
happen_fraud

                                  merchant      category  is_fraud
0        fraud_Herman, Treutel and Dickens      misc_net  0.022433
1                         fraud_Terry-Huel  shopping_net  0.021765
2                          fraud_Brown PLC      misc_net  0.021442
3                        fraud_Goyette Inc  shopping_net  0.021097
4                       fraud_Rau and Sons   grocery_pos  0.020930
..                                     ...           ...       ...
695  fraud_Hodkiewicz, Prohaska and Paucek        travel  0.000000
696                      fraud_Trantow PLC   grocery_net  0.000000
697                fraud_Reichert-Weissnat        travel  0.000000
698                      fraud_Windler LLC     kids_pets  0.000000
699                   fraud_Mosciski Group        travel  0.000000

[700 rows x 3 columns]

In [45]:
train = pd.merge(train, happen_fraud, how='left', on=['merchant', 'category'])
train

,trans_date_trans_time,cc_num,merchant,category,amt,gender,lat,long,city_pop,job,...,merch_lat,merch_long,is_fraud_x,mean_train,std_train,amt_z_scroe,mean_amtbycategory,std_amtbycategory,category_z_score,is_fraud_y
0,2020-07-09 06:53:00,377895991033232,fraud_Zboncak Ltd,food_dining,130.680000,F,41.468200,-72.575100,5438,"Librarian, academic",...,41.809910,-73.494581,0,73.414795,131.574335,0.435231,77.601548,45.818777,0.435231,0.001277
1,2019-08-08 18:20:52,38588538868506,fraud_Fritsch and Sons,health_fitness,54.460000,F,30.188600,-103.221400,498,Lexicographer,...,30.858585,-102.458928,0,59.766495,147.773396,-0.035910,47.625806,47.145251,-0.035910,0.001370
2,2019-12-29 14:00:23,349612764943496,fraud_Windler LLC,kids_pets,42.420000,M,37.104600,-83.570600,467,"Psychologist, forensic",...,36.405837,-84.030634,0,97.885517,103.125597,-0.537844,49.757807,4.623726,-0.537844,0.000000
3,2019-08-16 18:02:28,4874017206859125,"fraud_Prosacco, Kreiger and Kovacek",home,77.050000,F,45.409300,-122.684700,42817,Planning and development surveyor,...,46.111612,-121.729974,0,89.205841,127.017879,-0.095702,60.795242,47.326641,-0.095702,0.000483
4,2020-04-14 00:21:46,5501083170975659,fraud_Jast Ltd,shopping_net,1.950000,M,41.146400,-81.510700,47772,Equities trader,...,40.945120,-82.361809,0,63.371306,112.601803,-0.545474,95.786579,209.203479,-0.545474,0.017136
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1111431,2020-07-14 19:29:36,676369110710,fraud_Nienow PLC,entertainment,11.330000,M,42.496900,-83.291100,75830,"Engineer, automotive",...,41.566847,-84.015768,0,59.117192,149.629935,-0.319369,71.607939,91.758240,-0.319369,0.002382
1111432,2019-03-02 15:25:33,30238755902988,fraud_Macejkovic-Lesch,shopping_pos,4.870000,F,30.592000,-97.289300,1766,Press sub,...,30.892429,-97.713717,0,54.625542,131.268419,-0.379037,53.431014,304.858339,-0.379037,0.008722
1111433,2019-09-13 03:44:55,4099707841315751,fraud_Hackett-Lueilwitz,grocery_pos,70.320000,M,38.258600,-78.407400,9815,"Designer, ceramics/pottery",...,38.195483,-78.668541,0,62.540364,293.792067,0.026480,64.247117,34.855381,0.026480,0.011353
1111434,2020-12-15 16:09:57,345933964507467,"fraud_Wuckert, Wintheiser and Friesen",home,121.300000,F,38.412100,-75.281100,718,Regulatory affairs officer,...,38.001255,-76.190657,0,55.467010,99.480757,0.661766,50.198143,50.149951,0.661766,0.003351
1111435,2020-08-28 03:24:55,4158008602445,fraud_Huels-Hahn,gas_transport,59.210000,F,44.527400,-93.019600,1201,Barrister,...,44.272907,-93.548241,0,53.571404,100.104338,0.056327,59.730952,13.972844,0.056327,0.003429

In [46]:
train['city_pop'].nunique()

891

In [49]:
train.columns

Index(['trans_date_trans_time', 'cc_num', 'merchant', 'category', 'amt',
       'gender', 'lat', 'long', 'city_pop', 'job', 'dob', 'merch_lat',
       'merch_long', 'is_fraud_x', 'mean_train', 'std_train', 'amt_z_scroe',
       'mean_amtbycategory', 'std_amtbycategory', 'category_z_score',
       'is_fraud_y'],
      dtype='object')

In [50]:
train.groupby('city_pop')[''].mean().sort_values(ascending=False)

city_pop
3164     1.000000
7339     1.000000
7322     1.000000
31702    1.000000
28506    1.000000
           ...
9594     0.000000
760      0.000000
18182    0.000000
254282   0.000000
13983    0.000000
Name: is_fraud_x, Length: 891, dtype: float64

In [51]:
train.groupby('city_pop')['is_fraud_x'].value_counts()

city_pop  is_fraud_x
23        0             1743
          1                4
37        0              905
          1                2
43        0             1740
                        ...
2383912   1                3
2504700   0             1775
          1                8
2906700   0             3512
          1               21
Name: count, Length: 1694, dtype: int64

In [57]:
# 각 city_pop에서 is_fraud가 일어난 비율을 계산
fraudbypop = train.groupby(['city_pop', 'is_fraud_x'])['is_fraud_x'].count().unstack()

# is_fraud가 일어난 비율 계산 (시가 가격대 비율)
fraudbypop['fraud_ratio'] = fraudbypop[1] / fraudbypop.sum(axis=1)

# 결과값 출력
print(fraudbypop[['fraud_ratio']])

is_fraud_x  fraud_ratio
city_pop
23             0.002290
37             0.002205
43                  NaN
46             0.002683
47             0.004494
...                 ...
1577385        0.010417
1595797        0.003404
2383912        0.006579
2504700        0.004487
2906700        0.005944

[891 rows x 1 columns]

In [ ]:
#카드 거래 피해자 성별

In [52]:
train.groupby('gender')['is_fraud_x'].value_counts()

gender  is_fraud_x
F       0             605978
        1               2958
M       0             499667
        1               2833
Name: count, dtype: int64

In [54]:
train['job'].value_counts()

job
Film/video editor             8439
Exhibition designer           7883
Surveyor, land/geomatics      7461
Naval architect               7376
Designer, ceramics/pottery    6962
                              ...
Veterinary surgeon               4
Engineer, water                  4
Contracting civil engineer       4
Industrial buyer                 3
Forest/woodland manager          2
Name: count, Length: 497, dtype: int64

In [55]:
train.groupby('job')['is_fraud_x'].value_counts(0)

job                              is_fraud_x
Academic librarian               0              896
                                 1                9
Accountant, chartered            1                6
Accountant, chartered certified  0              436
                                 1               10
                                               ...
Web designer                     1               10
Wellsite geologist               0             2227
                                 1               19
Writer                           0              444
                                 1               10
Name: count, Length: 969, dtype: int64

In [59]:
# 각 city_pop에서 is_fraud가 일어난 비율을 계산
fraudbyjob = train.groupby(['job', 'is_fraud_x'])['is_fraud_x'].count().unstack()

# is_fraud가 일어난 비율 계산 (시가 가격대 비율)
fraudbyjob['fraud_ratio'] = fraudbyjob[1] / fraudbyjob.sum(axis=1)

# 결과값 출력
print(fraudbyjob[['fraud_ratio']])

is_fraud_x                            fraud_ratio
job
Academic librarian                       0.009945
Accountant, chartered                    1.000000
Accountant, chartered certified          0.022422
Accountant, chartered public finance     0.002260
Accounting technician                    0.005338
...                                           ...
Water engineer                           0.002113
Water quality scientist                  0.007126
Web designer                             0.004525
Wellsite geologist                       0.008459
Writer                                   0.022026

[497 rows x 1 columns]

In [60]:
print(fraudbyjob[['fraud_ratio']].sort_values(by='fraud_ratio', ascending=False))

is_fraud_x                         fraud_ratio
job
Sales promotion account executive     1.000000
Dancer                                1.000000
Industrial buyer                      1.000000
Engineer, site                        1.000000
Air traffic controller                1.000000
...                                        ...
Aid worker                            0.000573
Contractor                            0.000375
Engineer, communications                   NaN
Engineer, drilling                         NaN
Stage manager                              NaN

[497 rows x 1 columns]

In [61]:
train['trans_date_trans_time'] = pd.to_datetime(train['trans_date_trans_time'])

In [62]:
train['trans_date_trans_time'].dtype

dtype('<M8[ns]')

In [63]:
train['trans_date_trans_time'].apply(lambda x: x.year)

0          2020
1          2019
2          2019
3          2019
4          2020
           ...
1111431    2020
1111432    2019
1111433    2019
1111434    2020
1111435    2020
Name: trans_date_trans_time, Length: 1111436, dtype: int64

In [64]:
train['age'] = train['dob'].apply(lambda x: 2020-int(x[:4]))

In [65]:
train

,trans_date_trans_time,cc_num,merchant,category,amt,gender,lat,long,city_pop,job,...,merch_long,is_fraud_x,mean_train,std_train,amt_z_scroe,mean_amtbycategory,std_amtbycategory,category_z_score,is_fraud_y,age
0,2020-07-09 06:53:00,377895991033232,fraud_Zboncak Ltd,food_dining,130.680000,F,41.468200,-72.575100,5438,"Librarian, academic",...,-73.494581,0,73.414795,131.574335,0.435231,77.601548,45.818777,0.435231,0.001277,56
1,2019-08-08 18:20:52,38588538868506,fraud_Fritsch and Sons,health_fitness,54.460000,F,30.188600,-103.221400,498,Lexicographer,...,-102.458928,0,59.766495,147.773396,-0.035910,47.625806,47.145251,-0.035910,0.001370,30
2,2019-12-29 14:00:23,349612764943496,fraud_Windler LLC,kids_pets,42.420000,M,37.104600,-83.570600,467,"Psychologist, forensic",...,-84.030634,0,97.885517,103.125597,-0.537844,49.757807,4.623726,-0.537844,0.000000,36
3,2019-08-16 18:02:28,4874017206859125,"fraud_Prosacco, Kreiger and Kovacek",home,77.050000,F,45.409300,-122.684700,42817,Planning and development surveyor,...,-121.729974,0,89.205841,127.017879,-0.095702,60.795242,47.326641,-0.095702,0.000483,38
4,2020-04-14 00:21:46,5501083170975659,fraud_Jast Ltd,shopping_net,1.950000,M,41.146400,-81.510700,47772,Equities trader,...,-82.361809,0,63.371306,112.601803,-0.545474,95.786579,209.203479,-0.545474,0.017136,54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1111431,2020-07-14 19:29:36,676369110710,fraud_Nienow PLC,entertainment,11.330000,M,42.496900,-83.291100,75830,"Engineer, automotive",...,-84.015768,0,59.117192,149.629935,-0.319369,71.607939,91.758240,-0.319369,0.002382,46
1111432,2019-03-02 15:25:33,30238755902988,fraud_Macejkovic-Lesch,shopping_pos,4.870000,F,30.592000,-97.289300,1766,Press sub,...,-97.713717,0,54.625542,131.268419,-0.379037,53.431014,304.858339,-0.379037,0.008722,44
1111433,2019-09-13 03:44:55,4099707841315751,fraud_Hackett-Lueilwitz,grocery_pos,70.320000,M,38.258600,-78.407400,9815,"Designer, ceramics/pottery",...,-78.668541,0,62.540364,293.792067,0.026480,64.247117,34.855381,0.026480,0.011353,45
1111434,2020-12-15 16:09:57,345933964507467,"fraud_Wuckert, Wintheiser and Friesen",home,121.300000,F,38.412100,-75.281100,718,Regulatory affairs officer,...,-76.190657,0,55.467010,99.480757,0.661766,50.198143,50.149951,0.661766,0.003351,35
1111435,2020-08-28 03:24:55,4158008602445,fraud_Huels-Hahn,gas_transport,59.210000,F,44.527400,-93.019600,1201,Barrister,...,-93.548241,0,53.571404,100.104338,0.056327,59.730952,13.972844,0.056327,0.003429,41

# 위도 경도 정보로 거리 계산하기

In [67]:
!pip install geopy

Collecting geopy
  Downloading geopy-2.4.1-py3-none-any.whl.metadata (6.8 kB)
Collecting geographiclib<3,>=1.52 (from geopy)
  Downloading geographiclib-2.0-py3-none-any.whl.metadata (1.4 kB)
Downloading geopy-2.4.1-py3-none-any.whl (125 kB)
   ---------------------------------------- 0.0/125.4 kB ? eta -:--:--
   --------- ------------------------------ 30.7/125.4 kB 1.4 MB/s eta 0:00:01
   ---------------------------------------- 125.4/125.4 kB 2.5 MB/s eta 0:00:00
Downloading geographiclib-2.0-py3-none-any.whl (40 kB)
   ---------------------------------------- 0.0/40.3 kB ? eta -:--:--
   ---------------------------------------- 40.3/40.3 kB 1.9 MB/s eta 0:00:00
Installing collected packages: geographiclib, geopy
Successfully installed geographiclib-2.0 geopy-2.4.1

In [68]:
import geopy.distance

In [69]:
train['customer_coord'] = pd.Series(zip(train['lat'], train['long']))
train['merchant_coord'] = pd.Series(zip(train['merch_lat'], train['merch_long']))

In [70]:
train

,trans_date_trans_time,cc_num,merchant,category,amt,gender,lat,long,city_pop,job,...,mean_train,std_train,amt_z_scroe,mean_amtbycategory,std_amtbycategory,category_z_score,is_fraud_y,age,customer_coord,merchant_coord
0,2020-07-09 06:53:00,377895991033232,fraud_Zboncak Ltd,food_dining,130.680000,F,41.468200,-72.575100,5438,"Librarian, academic",...,73.414795,131.574335,0.435231,77.601548,45.818777,0.435231,0.001277,56,"(41.4682, -72.5751)","(41.80991, -73.49458100000001)"
1,2019-08-08 18:20:52,38588538868506,fraud_Fritsch and Sons,health_fitness,54.460000,F,30.188600,-103.221400,498,Lexicographer,...,59.766495,147.773396,-0.035910,47.625806,47.145251,-0.035910,0.001370,30,"(30.1886, -103.2214)","(30.858585, -102.458928)"
2,2019-12-29 14:00:23,349612764943496,fraud_Windler LLC,kids_pets,42.420000,M,37.104600,-83.570600,467,"Psychologist, forensic",...,97.885517,103.125597,-0.537844,49.757807,4.623726,-0.537844,0.000000,36,"(37.1046, -83.5706)","(36.405837, -84.03063399999999)"
3,2019-08-16 18:02:28,4874017206859125,"fraud_Prosacco, Kreiger and Kovacek",home,77.050000,F,45.409300,-122.684700,42817,Planning and development surveyor,...,89.205841,127.017879,-0.095702,60.795242,47.326641,-0.095702,0.000483,38,"(45.4093, -122.6847)","(46.111612, -121.729974)"
4,2020-04-14 00:21:46,5501083170975659,fraud_Jast Ltd,shopping_net,1.950000,M,41.146400,-81.510700,47772,Equities trader,...,63.371306,112.601803,-0.545474,95.786579,209.203479,-0.545474,0.017136,54,"(41.1464, -81.5107)","(40.94512, -82.361809)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1111431,2020-07-14 19:29:36,676369110710,fraud_Nienow PLC,entertainment,11.330000,M,42.496900,-83.291100,75830,"Engineer, automotive",...,59.117192,149.629935,-0.319369,71.607939,91.758240,-0.319369,0.002382,46,"(42.4969, -83.2911)","(41.566847, -84.01576800000001)"
1111432,2019-03-02 15:25:33,30238755902988,fraud_Macejkovic-Lesch,shopping_pos,4.870000,F,30.592000,-97.289300,1766,Press sub,...,54.625542,131.268419,-0.379037,53.431014,304.858339,-0.379037,0.008722,44,"(30.592, -97.2893)","(30.892429, -97.713717)"
1111433,2019-09-13 03:44:55,4099707841315751,fraud_Hackett-Lueilwitz,grocery_pos,70.320000,M,38.258600,-78.407400,9815,"Designer, ceramics/pottery",...,62.540364,293.792067,0.026480,64.247117,34.855381,0.026480,0.011353,45,"(38.2586, -78.4074)","(38.195483, -78.668541)"
1111434,2020-12-15 16:09:57,345933964507467,"fraud_Wuckert, Wintheiser and Friesen",home,121.300000,F,38.412100,-75.281100,718,Regulatory affairs officer,...,55.467010,99.480757,0.661766,50.198143,50.149951,0.661766,0.003351,35,"(38.4121, -75.2811)","(38.001255, -76.190657)"
1111435,2020-08-28 03:24:55,4158008602445,fraud_Huels-Hahn,gas_transport,59.210000,F,44.527400,-93.019600,1201,Barrister,...,53.571404,100.104338,0.056327,59.730952,13.972844,0.056327,0.003429,41,"(44.5274, -93.0196)","(44.272907, -93.548241)"

In [71]:
train['distance'] = train.apply(lambda x: geopy.distance.distance(x['customer_coord'], x['merchant_coord']).km, axis=1)

In [72]:
train

,trans_date_trans_time,cc_num,merchant,category,amt,gender,lat,long,city_pop,job,...,std_train,amt_z_scroe,mean_amtbycategory,std_amtbycategory,category_z_score,is_fraud_y,age,customer_coord,merchant_coord,distance
0,2020-07-09 06:53:00,377895991033232,fraud_Zboncak Ltd,food_dining,130.680000,F,41.468200,-72.575100,5438,"Librarian, academic",...,131.574335,0.435231,77.601548,45.818777,0.435231,0.001277,56,"(41.4682, -72.5751)","(41.80991, -73.49458100000001)",85.493659
1,2019-08-08 18:20:52,38588538868506,fraud_Fritsch and Sons,health_fitness,54.460000,F,30.188600,-103.221400,498,Lexicographer,...,147.773396,-0.035910,47.625806,47.145251,-0.035910,0.001370,30,"(30.1886, -103.2214)","(30.858585, -102.458928)",104.268083
2,2019-12-29 14:00:23,349612764943496,fraud_Windler LLC,kids_pets,42.420000,M,37.104600,-83.570600,467,"Psychologist, forensic",...,103.125597,-0.537844,49.757807,4.623726,-0.537844,0.000000,36,"(37.1046, -83.5706)","(36.405837, -84.03063399999999)",87.752495
3,2019-08-16 18:02:28,4874017206859125,"fraud_Prosacco, Kreiger and Kovacek",home,77.050000,F,45.409300,-122.684700,42817,Planning and development surveyor,...,127.017879,-0.095702,60.795242,47.326641,-0.095702,0.000483,38,"(45.4093, -122.6847)","(46.111612, -121.729974)",107.748245
4,2020-04-14 00:21:46,5501083170975659,fraud_Jast Ltd,shopping_net,1.950000,M,41.146400,-81.510700,47772,Equities trader,...,112.601803,-0.545474,95.786579,209.203479,-0.545474,0.017136,54,"(41.1464, -81.5107)","(40.94512, -82.361809)",74.968301
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1111431,2020-07-14 19:29:36,676369110710,fraud_Nienow PLC,entertainment,11.330000,M,42.496900,-83.291100,75830,"Engineer, automotive",...,149.629935,-0.319369,71.607939,91.758240,-0.319369,0.002382,46,"(42.4969, -83.2911)","(41.566847, -84.01576800000001)",119.468278
1111432,2019-03-02 15:25:33,30238755902988,fraud_Macejkovic-Lesch,shopping_pos,4.870000,F,30.592000,-97.289300,1766,Press sub,...,131.268419,-0.379037,53.431014,304.858339,-0.379037,0.008722,44,"(30.592, -97.2893)","(30.892429, -97.713717)",52.546596
1111433,2019-09-13 03:44:55,4099707841315751,fraud_Hackett-Lueilwitz,grocery_pos,70.320000,M,38.258600,-78.407400,9815,"Designer, ceramics/pottery",...,293.792067,0.026480,64.247117,34.855381,0.026480,0.011353,45,"(38.2586, -78.4074)","(38.195483, -78.668541)",23.914997
1111434,2020-12-15 16:09:57,345933964507467,"fraud_Wuckert, Wintheiser and Friesen",home,121.300000,F,38.412100,-75.281100,718,Regulatory affairs officer,...,99.480757,0.661766,50.198143,50.149951,0.661766,0.003351,35,"(38.4121, -75.2811)","(38.001255, -76.190657)",91.792859
1111435,2020-08-28 03:24:55,4158008602445,fraud_Huels-Hahn,gas_transport,59.210000,F,44.527400,-93.019600,1201,Barrister,...,100.104338,0.056327,59.730952,13.972844,0.056327,0.003429,41,"(44.5274, -93.0196)","(44.272907, -93.548241)",50.727824

In [73]:
train['distance'].describe()

count   1111436.000000
mean         76.100343
std          29.105449
min           0.066731
25%          55.315355
50%          78.236746
75%          98.467537
max         150.580192
Name: distance, dtype: float64