In [11]:
import requests
import pandas as pd
import os
from dotenv import load_dotenv
load_dotenv()
from naver_api_info

SyntaxError: invalid syntax (3477412409.py, line 6)

In [9]:
url = "https://openapi.naver.com/v1/search/news.json"
payload = {'query' : '핀테크', 'display' : 100, 'start' : 1, 'sort' : 'sim'}
headers = {'X-Naver-Client-Id' : client_id, 'X-Naver-Client-Secret' : client_secret}
r = requests.get(url, params = payload, headers = headers)
print(r.url)
if(r.status_code ==200):
    data = r.json()
else:
    print("Error Code:" + r.status_code)

NameError: name 'client_id' is not defined

In [5]:
df = pd.json_normalize(data['items'])
df

,title,originallink,link,description,pubDate
0,티몬·위메프 사태 파장 직격탄에 <b>핀테크</b>업계 ‘울상’,https://www.dailian.co.kr/news/view/1391156/?s...,https://n.news.naver.com/mnews/article/119/000...,위메프·티몬(티메프) 판매대금 정산 지연 사태로 인해 <b>핀테크</b> 업계에도 ...,"Fri, 02 Aug 2024 06:00:00 +0900"
1,[마켓인]코스닥 상장 뱅크웨어글로벌…한투파 &quot;<b>핀테크</b> 육성 결실...,http://www.edaily.co.kr/news/newspath.asp?news...,https://n.news.naver.com/mnews/article/018/000...,한국투자파트너스(한투파)가 운용 중인 <b>핀테크</b>혁신펀드에서 첫 코스닥 상장...,"Fri, 02 Aug 2024 08:21:00 +0900"
2,"아르고스, 코리아 <b>핀테크</b> 위크 2024 참가",https://www.etnews.com/20240801000339,https://n.news.naver.com/mnews/article/030/000...,코리아 <b>핀테크</b> 위크 2024에 참가한다. 아르고스는 비대면 환경에서 A...,"Thu, 01 Aug 2024 16:48:00 +0900"
3,"한투파트너스, '<b>핀테크</b>혁신펀드' 1호 상장 일궜다",https://www.newstof.com/news/articleView.html?...,https://www.newstof.com/news/articleView.html?...,한국투자금융지주 계열 벤처캐피탈인 한국투자파트너스가 <b>핀테크</b>혁신펀드 위탁...,"Fri, 02 Aug 2024 11:00:00 +0900"
4,"<b>핀테크</b> 업체들, 티몬·위메프 결제액 선환불 신청 접수 개시",https://www.yna.co.kr/view/AKR2024072802120001...,https://n.news.naver.com/mnews/article/001/001...,네이버페이는 48시간 이내 처리 약속 네이버페이 등 <b>핀테크</b> 업체들이 2...,"Sun, 28 Jul 2024 10:52:00 +0900"
...,...,...,...,...,...
95,"'폰고' 운영사 피에로컴퍼니, 법인향 IT기기 구독서비스 개시",http://news.mt.co.kr/mtview.php?no=20240801133...,https://n.news.naver.com/mnews/article/008/000...,리퍼비시 전자기기 구독 서비스 폰고(phoneGO)의 운영사 피에로컴퍼니가 <b>핀...,"Thu, 01 Aug 2024 20:45:00 +0900"
96,"네이버페이·토스, '티메프' 이용자 결제액 선환불 개시(종합)",https://www.yna.co.kr/view/AKR2024072907325101...,https://n.news.naver.com/mnews/article/001/001...,"네이버페이 &quot;48시간 이내 선환불 약속 지켜져&quot;…토스, 저녁 9시...","Mon, 29 Jul 2024 22:30:00 +0900"
97,"밸런스히어로, 24년 상반기 역대 최대 실적…플랫폼 매출 3배 급증",https://platum.kr/archives/232188,https://platum.kr/archives/232188,인도에 진출한 한국 <b>핀테크</b> 기업 밸런스히어로가 2024년 상반기 사상 ...,"Thu, 01 Aug 2024 11:48:00 +0900"
98,"서울시-신한은행·카드·증권, 유망 <b>핀테크</b> 기업 6곳 지원",http://www.fnnews.com/news/202407221121059535,https://n.news.naver.com/mnews/article/014/000...,서울시가 신한은행·신한카드·신한투자증권과 함께 잠재력을 가진 <b>핀테크</b> 기...,"Mon, 22 Jul 2024 11:22:00 +0900"
99,"신한금융-서울시, 혁신 <b>핀테크</b> 스타트업 6개사 선발 [은행·카드오늘]",http://www.sisaon.co.kr/news/articleView.html?...,http://www.sisaon.co.kr/news/articleView.html?...,"ⓒ신한은행 신한금융-서울시, 올해 혁신 <b>핀테크</b> 스타트업 6개사 선발 신...","Tue, 23 Jul 2024 15:52:00 +0900"

In [8]:
import os
import time
from sqlalchemy import create_engine, text
import pymysql
from env_db3 import db, dbtype, id, pw, host, database

ModuleNotFoundError: No module named 'env_db3'

In [ ]:
#pymysql을 MySQLdb로 설치
pymysql.install_as_MySQLdb()


#데이터베이스 엔진 생성
engine = create_engine("%s+%s://%s:%s@%s" % (db, dbtype, id, pw, host))
conn = engine.connect()

#데이터베이스가 없으면 생성
conn.execute(text('CREATE DATABASE IF NOT EXISTS naver_search_fintech'))
conn.close()

#DB에 접속해서 저장하는 함수
def exchange_rate(df):
    from sqlalchemy import create_engine
    import pymysql
    from dbenv2 import db, dbtype, id, pw, host, database
    from datetime import date
    pymysql.install_as_MySQLdb()

    today = str(date.today()).replace("-","")

    engine = create_engine("%s+%s://%s:%s@%s/%s" % (db, dbtype, id, pw, host, database))
    conn = engine.connect()
    df.to_sql(f"{today[:6]}korea_exchange_rate", con=conn, if_exists='append', index=False)
    conn.close()

    return print(f"{'저장완료':<30s}", end="\r")