# 반복문 for, while
* 반복문은 동일한 작업을 여러 번 반복해야 할 경우 사용하는 명령
* for, while 두 종류의 반복문이 있음.
* for는 반복 횟수가 정해져 있는 경우에 사용.
* while은 반복 횟수가 정해지지 않은 경우에 사용.

## for 반복문 : 반복할 횟수가 정해져 있는 경우
for 변수 in 반복할 객체, 자료:<br>
____반복할 코드

In [1]:
# for 문을 이용해서 1-10 숫자 출력
for i in range(1,11):
    print(i, end =" ")

1 2 3 4 5 6 7 8 9 10

* 순서가 있는 자료형은 모두 for 문에 사용 가능
    * 문자열, list, tuple

In [2]:
for char in "파이썬":
    print(char, end=" ")

파 이 썬

In [3]:
for item in [1, 2, 3, 4, 5]:
    print(item, end = " ")

1 2 3 4 5

In [4]:
L = [1,2,3,3, "문자열", [1,2,3], (4,5,6), {'key':'value'}]

In [5]:
for item in L:
    print(item, end = " ")

1 2 3 3 문자열 [1, 2, 3] (4, 5, 6) {'key': 'value'}

In [6]:
T = tuple(L)
for item in T:
    print(item, end = " ")

1 2 3 3 문자열 [1, 2, 3] (4, 5, 6) {'key': 'value'}

In [7]:
d = dict(번호=1, 주소='서울', 전화번호='010-1234-5678', 이름='홍길동')
for key in d:
    print(d[key], end=" ")
#딕셔너리는 반복문에 넣었을 때 key만 출력되므로, value 넣기 위해서는 key로 value 호출하기

1 서울 010-1234-5678 홍길동

In [8]:
for key in d:
    print(d.get(key,0), end = " ")
#key가 없으면 0으로 출력해라.

1 서울 010-1234-5678 홍길동

In [9]:
for k,v in d.items():
    print(k,v)

번호 1
주소 서울
전화번호 010-1234-5678
이름 홍길동

In [10]:
#for 반복문을 이용해서 1부터 10까지 정수를 더한 합만을 출력하세요.
L = []
for i in range(1,11):
    L.append(i)
print(sum(L))

55

In [11]:
#1~100까지 곱한 값을 출력하세요.
num = 1
for i in range(1,101):
    num *= i
print(num)

93326215443944152681699238856266700490715968264381621468592963895217599993229915608941463976156518286253697920827223758251185210916864000000000000000000000000

1~50까지 수 중에서 짝수인 수의 합을 구하시오.
* 1-50 수를 만들기
* 홀 짝 구분 if else
* 짝수면 덧셈 누적합
* print()

In [12]:
num = 0
for i in range(1,51):
    if i % 2 == 0:
        num += i
    else:
        pass
print(num)

650

In [13]:
#1부터 100까지의 수 중에서 7의 배수만 찾아 곱한 값을 출력하세요.
num = 1
for i in range(1,101):
    if i % 7 == 0:
        num *= i
    else:
        pass
print(num)

59126328543388935628800

In [23]:
#1부터 100까지 수를 만들고 그 중 30~70까지만 더해서 출력하세요.
num = 0
for i in range(1,101):
    if 30 <= i <= 70:
        num += i
    else:
        pass

print(num)

2050

In [24]:
my_list = list(range(1,101)) #range 슬라이싱할 때 인덱스 번호 달라지는 것 주의

sum(my_list[29:70])

2050

In [27]:
L1 = list(range(1,10,2))
L2 = list(range(0,10,2))
print(L1)
print(L2)

[1, 3, 5, 7, 9]
[0, 2, 4, 6, 8]

In [29]:
temp = 0
for num, num2 in zip(L1, L2):
    temp = num + num2
    print(num, num2, temp)

1 0 1
3 2 5
5 4 9
7 6 13
9 8 17

enumerate(): index를 만들어주는 함수

In [32]:
for index, char in enumerate("파이썬은 문자열을 반복문에 넣어 출력 가능"):
    print(index, char, end= "")

0 파1 이2 썬3 은4  5 문6 자7 열8 을9  10 반11 복12 문13 에14  15 넣16 어17  18 출19 력20  21 가22 능

In [36]:
for index, num1 in enumerate(zip(L1, L2)):
    print(num1)
    print(len(num1))

(1, 0)
2
(3, 2)
2
(5, 4)
2
(7, 6)
2
(9, 8)
2

1-10 까지 숫자를 만들고 역순으로 출력하세요

In [43]:
for num in range(10,0,-1):
    print(num, end= " ")

10 9 8 7 6 5 4 3 2 1

In [40]:
for num in reversed(range(1,11)):
    print(num, end= " ")

10 9 8 7 6 5 4 3 2 1

In [42]:
for num in range(1,11)[::-1]:
    print(num, end= " ")

10 9 8 7 6 5 4 3 2 1

In [11]:
for num in range(1,11, 2):
    print(num, end= " ")

1 3 5 7 9

# while 반복할 횟수가 정해지지 않은 경우
* 무한 반복 가능
* 무한 반복 되지 않도록 조건식을 잘 짜주는 것이 중요

In [ ]:
#while문을 이용해서 1-10까지 더해서 결과를 출력하세요.
i = 1
while i <= 10:
    print(i, end=" ")
    i += 1

In [ ]:
# 웹 크롤링시, while 많이 사용
# while문을 이용해서 1-10까지 더해서 결과를 출력하세요.
i = 1
hap = 0
while i <= 10:
    hap += i
    i += 1
print(hap)

In [ ]:
#20에서 1까지 숫자를 더한 값을 출력하세요.
i = 20
hap = 0
while i > 0:
    hap += i
    i -= 1
print(hap)

In [ ]:
#1-50 까지 수 중에서 3의 배수이거나, 짝수인 수를 찾아서 더한 값을 출력하시오.
i = 1
hap = 0
while i <= 50:
    if i % 3 == 0 or i % 2 ==0:
        hap += i
    i += 1
print(hap)

In [ ]:
# #반복 횟수가 정해지지 않은 경우: 무한반복
# while True:
#     print("무한반복")

반복문에서 아무일도 하지 않고 건너뛰기 : pass
* 우선 반복할 코드가 들어가야 하는 곳을 만들고 나중에 작업하기 위해 사용

In [ ]:
i = 1
while i <= 10:
    pass
    i += 1

Break 반복문을 정지시키는 명령

In [ ]:
for i in range(1.101):
    if i > 50:
        break
    else:
        print(i, end=" ")

# continue: 특정 조건에서 코드 실행 건너뛰기

In [ ]:
#1~100까지 수 중에서 짝수면 더하고 홀수면 건너뛰기
hap = 0
for i in range(1, 101):
    if i % 2 == 1:
        continue
    else:
        hap += i
        print(hap, end =" ")

In [13]:
#1~100까지 수 중에서 짝수면 더하고 홀수면 건너뛰기
i = 1
hap = 0

while i <= 100: 
    if i % 2 == 1:
        i += 1
        continue
    hap += i
    i += 1
    print(hap, end =" ")

2 6 12 20 30 42 56 72 90 110 132 156 182 210 240 272 306 342 380 420 462 506 552 600 650 702 756 812 870 930 992 1056 1122 1190 1260 1332 1406 1482 1560 1640 1722 1806 1892 1980 2070 2162 2256 2352 2450 2550

In [24]:
total = 0
i = 1

while True:
    if i > 100:
        break
    if i % 2 == 0:
        total += i
        print(total, end =" ")
    i += 1

2 6 12 20 30 42 56 72 90 110 132 156 182 210 240 272 306 342 380 420 462 506 552 600 650 702 756 812 870 930 992 1056 1122 1190 1260 1332 1406 1482 1560 1640 1722 1806 1892 1980 2070 2162 2256 2352 2450 2550

In [ ]:
## 중첩 반복문
* 반복문 2개 이상을 겹쳐서 사용
* 바늘 시계의 원리와 같음. (분침이 0~59까지 돌아야 시침이 한 칸 움직임)
* 안쪽 반복이 끝난 후 바깥쪽 반복문이 실행

In [21]:
for si in range(0, 24):
    for bun in range(0, 60):
        print(si, "시", bun, "분", end= " ")

0 시 0 분 0 시 1 분 0 시 2 분 0 시 3 분 0 시 4 분 0 시 5 분 0 시 6 분 0 시 7 분 0 시 8 분 0 시 9 분 0 시 10 분 0 시 11 분 0 시 12 분 0 시 13 분 0 시 14 분 0 시 15 분 0 시 16 분 0 시 17 분 0 시 18 분 0 시 19 분 0 시 20 분 0 시 21 분 0 시 22 분 0 시 23 분 0 시 24 분 0 시 25 분 0 시 26 분 0 시 27 분 0 시 28 분 0 시 29 분 0 시 30 분 0 시 31 분 0 시 32 분 0 시 33 분 0 시 34 분 0 시 35 분 0 시 36 분 0 시 37 분 0 시 38 분 0 시 39 분 0 시 40 분 0 시 41 분 0 시 42 분 0 시 43 분 0 시 44 분 0 시 45 분 0 시 46 분 0 시 47 분 0 시 48 분 0 시 49 분 0 시 50 분 0 시 51 분 0 시 52 분 0 시 53 분 0 시 54 분 0 시 55 분 0 시 56 분 0 시 57 분 0 시 58 분 0 시 59 분 1 시 0 분 1 시 1 분 1 시 2 분 1 시 3 분 1 시 4 분 1 시 5 분 1 시 6 분 1 시 7 분 1 시 8 분 1 시 9 분 1 시 10 분 1 시 11 분 1 시 12 분 1 시 13 분 1 시 14 분 1 시 15 분 1 시 16 분 1 시 17 분 1 시 18 분 1 시 19 분 1 시 20 분 1 시 21 분 1 시 22 분 1 시 23 분 1 시 24 분 1 시 25 분 1 시 26 분 1 시 27 분 1 시 28 분 1 시 29 분 1 시 30 분 1 시 31 분 1 시 32 분 1 시 33 분 1 시 34 분 1 시 35 분 1 시 36 분 1 시 37 분 1 시 38 분 1 시 39 분 1 시 40 분 1 시 41 분 1 시 42 분 1 시 43 분 1 시 44 분 1 시 45 분 1 시 46 분 1 시 47 분 1 시 48 분 1 시 49 분 1 시 50 분 1 시 51 분 1 시 52 분 1 시 53 분 1 시 54 분 1 시 55 분 1 시 56 분 1 시 57 분 1 시 58 분 1 시 59 분 2 시 0 분 2 시 1 분 2 시 2 분 2 시 3 분 2 시 4 분 2 시 5 분 2 시 6 분 2 시 7 분 2 시 8 분 2 시 9 분 2 시 10 분 2 시 11 분 2 시 12 분 2 시 13 분 2 시 14 분 2 시 15 분 2 시 16 분 2 시 17 분 2 시 18 분 2 시 19 분 2 시 20 분 2 시 21 분 2 시 22 분 2 시 23 분 2 시 24 분 2 시 25 분 2 시 26 분 2 시 27 분 2 시 28 분 2 시 29 분 2 시 30 분 2 시 31 분 2 시 32 분 2 시 33 분 2 시 34 분 2 시 35 분 2 시 36 분 2 시 37 분 2 시 38 분 2 시 39 분 2 시 40 분 2 시 41 분 2 시 42 분 2 시 43 분 2 시 44 분 2 시 45 분 2 시 46 분 2 시 47 분 2 시 48 분 2 시 49 분 2 시 50 분 2 시 51 분 2 시 52 분 2 시 53 분 2 시 54 분 2 시 55 분 2 시 56 분 2 시 57 분 2 시 58 분 2 시 59 분 3 시 0 분 3 시 1 분 3 시 2 분 3 시 3 분 3 시 4 분 3 시 5 분 3 시 6 분 3 시 7 분 3 시 8 분 3 시 9 분 3 시 10 분 3 시 11 분 3 시 12 분 3 시 13 분 3 시 14 분 3 시 15 분 3 시 16 분 3 시 17 분 3 시 18 분 3 시 19 분 3 시 20 분 3 시 21 분 3 시 22 분 3 시 23 분 3 시 24 분 3 시 25 분 3 시 26 분 3 시 27 분 3 시 28 분 3 시 29 분 3 시 30 분 3 시 31 분 3 시 32 분 3 시 33 분 3 시 34 분 3 시 35 분 3 시 36 분 3 시 37 분 3 시 38 분 3 시 39 분 3 시 40 분 3 시 41 분 3 시 42 분 3 시 43 분 3 시 44 분 3 시 45 분 3 시 46 분 3 시 47 분 3 시 48 분 3 시 49 분 3 시 50 분 3 시 51 분 3 시 52 분 3 시 53 분 3 시 54 분 3 시 55 분 3 시 56 분 3 시 57 분 3 시 58 분 3 시 59 분 4 시 0 분 4 시 1 분 4 시 2 분 4 시 3 분 4 시 4 분 4 시 5 분 4 시 6 분 4 시 7 분 4 시 8 분 4 시 9 분 4 시 10 분 4 시 11 분 4 시 12 분 4 시 13 분 4 시 14 분 4 시 15 분 4 시 16 분 4 시 17 분 4 시 18 분 4 시 19 분 4 시 20 분 4 시 21 분 4 시 22 분 4 시 23 분 4 시 24 분 4 시 25 분 4 시 26 분 4 시 27 분 4 시 28 분 4 시 29 분 4 시 30 분 4 시 31 분 4 시 32 분 4 시 33 분 4 시 34 분 4 시 35 분 4 시 36 분 4 시 37 분 4 시 38 분 4 시 39 분 4 시 40 분 4 시 41 분 4 시 42 분 4 시 43 분 4 시 44 분 4 시 45 분 4 시 46 분 4 시 47 분 4 시 48 분 4 시 49 분 4 시 50 분 4 시 51 분 4 시 52 분 4 시 53 분 4 시 54 분 4 시 55 분 4 시 56 분 4 시 57 분 4 시 58 분 4 시 59 분 5 시 0 분 5 시 1 분 5 시 2 분 5 시 3 분 5 시 4 분 5 시 5 분 5 시 6 분 5 시 7 분 5 시 8 분 5 시 9 분 5 시 10 분 5 시 11 분 5 시 12 분 5 시 13 분 5 시 14 분 5 시 15 분 5 시 16 분 5 시 17 분 5 시 18 분 5 시 19 분 5 시 20 분 5 시 21 분 5 시 22 분 5 시 23 분 5 시 24 분 5 시 25 분 5 시 26 분 5 시 27 분 5 시 28 분 5 시 29 분 5 시 30 분 5 시 31 분 5 시 32 분 5 시 33 분 5 시 34 분 5 시 35 분 5 시 36 분 5 시 37 분 5 시 38 분 5 시 39 분 5 시 40 분 5 시 41 분 5 시 42 분 5 시 43 분 5 시 44 분 5 시 45 분 5 시 46 분 5 시 47 분 5 시 48 분 5 시 49 분 5 시 50 분 5 시 51 분 5 시 52 분 5 시 53 분 5 시 54 분 5 시 55 분 5 시 56 분 5 시 57 분 5 시 58 분 5 시 59 분 6 시 0 분 6 시 1 분 6 시 2 분 6 시 3 분 6 시 4 분 6 시 5 분 6 시 6 분 6 시 7 분 6 시 8 분 6 시 9 분 6 시 10 분 6 시 11 분 6 시 12 분 6 시 13 분 6 시 14 분 6 시 15 분 6 시 16 분 6 시 17 분 6 시 18 분 6 시 19 분 6 시 20 분 6 시 21 분 6 시 22 분 6 시 23 분 6 시 24 분 6 시 25 분 6 시 26 분 6 시 27 분 6 시 28 분 6 시 29 분 6 시 30 분 6 시 31 분 6 시 32 분 6 시 33 분 6 시 34 분 6 시 35 분 6 시 36 분 6 시 37 분 6 시 38 분 6 시 39 분 6 시 40 분 6 시 41 분 6 시 42 분 6 시 43 분 6 시 44 분 6 시 45 분 6 시 46 분 6 시 47 분 6 시 48 분 6 시 49 분 6 시 50 분 6 시 51 분 6 시 52 분 6 시 53 분 6 시 54 분 6 시 55 분 6 시 56 분 6 시 57 분 6 시 58 분 6 시 59 분 7 시 0 분 7 시 1 분 7 시 2 분 7 시 3 분 7 시 4 분 7 시 5 분 7 시 6 분 7 시 7 분 7 시 8 분 7 시 9 분 7 시 10 분 7 시 11 분 7 시 12 분 7 시 13 분 7 시 14 분 7 시 15 분 7 시 16 분 7 시 17 분 7 시 18 분 7 시 19 분 7 시 20 분 7 시 21 분 7 시 22 분 7 시 23 분 7 시 24 분 7 시 25 분 7 시 26 분 7 시 27 분 7 시 28 분 7 시 29 분 7 시 30 분 7 시 31 분 7 시 32 분 7 시 33 분 7 시 34 분 7 시 35 분 7 시 36 분 7 시 37 분 7 시 38 분 7 시 39 분 7 시 40 분 7 시 41 분 7 시 42 분 7 시 43 분 7 시 44 분 7 시 45 분 7 시 46 분 7 시 47 분 7 시 48 분 7 시 49 분 7 시 50 분 7 시 51 분 7 시 52 분 7 시 53 분 7 시 54 분 7 시 55 분 7 시 56 분 7 시 57 분 7 시 58 분 7 시 59 분 8 시 0 분 8 시 1 분 8 시 2 분 8 시 3 분 8 시 4 분 8 시 5 분 8 시 6 분 8 시 7 분 8 시 8 분 8 시 9 분 8 시 10 분 8 시 11 분 8 시 12 분 8 시 13 분 8 시 14 분 8 시 15 분 8 시 16 분 8 시 17 분 8 시 18 분 8 시 19 분 8 시 20 분 8 시 21 분 8 시 22 분 8 시 23 분 8 시 24 분 8 시 25 분 8 시 26 분 8 시 27 분 8 시 28 분 8 시 29 분 8 시 30 분 8 시 31 분 8 시 32 분 8 시 33 분 8 시 34 분 8 시 35 분 8 시 36 분 8 시 37 분 8 시 38 분 8 시 39 분 8 시 40 분 8 시 41 분 8 시 42 분 8 시 43 분 8 시 44 분 8 시 45 분 8 시 46 분 8 시 47 분 8 시 48 분 8 시 49 분 8 시 50 분 8 시 51 분 8 시 52 분 8 시 53 분 8 시 54 분 8 시 55 분 8 시 56 분 8 시 57 분 8 시 58 분 8 시 59 분 9 시 0 분 9 시 1 분 9 시 2 분 9 시 3 분 9 시 4 분 9 시 5 분 9 시 6 분 9 시 7 분 9 시 8 분 9 시 9 분 9 시 10 분 9 시 11 분 9 시 12 분 9 시 13 분 9 시 14 분 9 시 15 분 9 시 16 분 9 시 17 분 9 시 18 분 9 시 19 분 9 시 20 분 9 시 21 분 9 시 22 분 9 시 23 분 9 시 24 분 9 시 25 분 9 시 26 분 9 시 27 분 9 시 28 분 9 시 29 분 9 시 30 분 9 시 31 분 9 시 32 분 9 시 33 분 9 시 34 분 9 시 35 분 9 시 36 분 9 시 37 분 9 시 38 분 9 시 39 분 9 시 40 분 9 시 41 분 9 시 42 분 9 시 43 분 9 시 44 분 9 시 45 분 9 시 46 분 9 시 47 분 9 시 48 분 9 시 49 분 9 시 50 분 9 시 51 분 9 시 52 분 9 시 53 분 9 시 54 분 9 시 55 분 9 시 56 분 9 시 57 분 9 시 58 분 9 시 59 분 10 시 0 분 10 시 1 분 10 시 2 분 10 시 3 분 10 시 4 분 10 시 5 분 10 시 6 분 10 시 7 분 10 시 8 분 10 시 9 분 10 시 10 분 10 시 11 분 10 시 12 분 10 시 13 분 10 시 14 분 10 시 15 분 10 시 16 분 10 시 17 분 10 시 18 분 10 시 19 분 10 시 20 분 10 시 21 분 10 시 22 분 10 시 23 분 10 시 24 분 10 시 25 분 10 시 26 분 10 시 27 분 10 시 28 분 10 시 29 분 10 시 30 분 10 시 31 분 10 시 32 분 10 시 33 분 10 시 34 분 10 시 35 분 10 시 36 분 10 시 37 분 10 시 38 분 10 시 39 분 10 시 40 분 10 시 41 분 10 시 42 분 10 시 43 분 10 시 44 분 10 시 45 분 10 시 46 분 10 시 47 분 10 시 48 분 10 시 49 분 10 시 50 분 10 시 51 분 10 시 52 분 10 시 53 분 10 시 54 분 10 시 55 분 10 시 56 분 10 시 57 분 10 시 58 분 10 시 59 분 11 시 0 분 11 시 1 분 11 시 2 분 11 시 3 분 11 시 4 분 11 시 5 분 11 시 6 분 11 시 7 분 11 시 8 분 11 시 9 분 11 시 10 분 11 시 11 분 11 시 12 분 11 시 13 분 11 시 14 분 11 시 15 분 11 시 16 분 11 시 17 분 11 시 18 분 11 시 19 분 11 시 20 분 11 시 21 분 11 시 22 분 11 시 23 분 11 시 24 분 11 시 25 분 11 시 26 분 11 시 27 분 11 시 28 분 11 시 29 분 11 시 30 분 11 시 31 분 11 시 32 분 11 시 33 분 11 시 34 분 11 시 35 분 11 시 36 분 11 시 37 분 11 시 38 분 11 시 39 분 11 시 40 분 11 시 41 분 11 시 42 분 11 시 43 분 11 시 44 분 11 시 45 분 11 시 46 분 11 시 47 분 11 시 48 분 11 시 49 분 11 시 50 분 11 시 51 분 11 시 52 분 11 시 53 분 11 시 54 분 11 시 55 분 11 시 56 분 11 시 57 분 11 시 58 분 11 시 59 분 12 시 0 분 12 시 1 분 12 시 2 분 12 시 3 분 12 시 4 분 12 시 5 분 12 시 6 분 12 시 7 분 12 시 8 분 12 시 9 분 12 시 10 분 12 시 11 분 12 시 12 분 12 시 13 분 12 시 14 분 12 시 15 분 12 시 16 분 12 시 17 분 12 시 18 분 12 시 19 분 12 시 20 분 12 시 21 분 12 시 22 분 12 시 23 분 12 시 24 분 12 시 25 분 12 시 26 분 12 시 27 분 12 시 28 분 12 시 29 분 12 시 30 분 12 시 31 분 12 시 32 분 12 시 33 분 12 시 34 분 12 시 35 분 12 시 36 분 12 시 37 분 12 시 38 분 12 시 39 분 12 시 40 분 12 시 41 분 12 시 42 분 12 시 43 분 12 시 44 분 12 시 45 분 12 시 46 분 12 시 47 분 12 시 48 분 12 시 49 분 12 시 50 분 12 시 51 분 12 시 52 분 12 시 53 분 12 시 54 분 12 시 55 분 12 시 56 분 12 시 57 분 12 시 58 분 12 시 59 분 13 시 0 분 13 시 1 분 13 시 2 분 13 시 3 분 13 시 4 분 13 시 5 분 13 시 6 분 13 시 7 분 13 시 8 분 13 시 9 분 13 시 10 분 13 시 11 분 13 시 12 분 13 시 13 분 13 시 14 분 13 시 15 분 13 시 16 분 13 시 17 분 13 시 18 분 13 시 19 분 13 시 20 분 13 시 21 분 13 시 22 분 13 시 23 분 13 시 24 분 13 시 25 분 13 시 26 분 13 시 27 분 13 시 28 분 13 시 29 분 13 시 30 분 13 시 31 분 13 시 32 분 13 시 33 분 13 시 34 분 13 시 35 분 13 시 36 분 13 시 37 분 13 시 38 분 13 시 39 분 13 시 40 분 13 시 41 분 13 시 42 분 13 시 43 분 13 시 44 분 13 시 45 분 13 시 46 분 13 시 47 분 13 시 48 분 13 시 49 분 13 시 50 분 13 시 51 분 13 시 52 분 13 시 53 분 13 시 54 분 13 시 55 분 13 시 56 분 13 시 57 분 13 시 58 분 13 시 59 분 14 시 0 분 14 시 1 분 14 시 2 분 14 시 3 분 14 시 4 분 14 시 5 분 14 시 6 분 14 시 7 분 14 시 8 분 14 시 9 분 14 시 10 분 14 시 11 분 14 시 12 분 14 시 13 분 14 시 14 분 14 시 15 분 14 시 16 분 14 시 17 분 14 시 18 분 14 시 19 분 14 시 20 분 14 시 21 분 14 시 22 분 14 시 23 분 14 시 24 분 14 시 25 분 14 시 26 분 14 시 27 분 14 시 28 분 14 시 29 분 14 시 30 분 14 시 31 분 14 시 32 분 14 시 33 분 14 시 34 분 14 시 35 분 14 시 36 분 14 시 37 분 14 시 38 분 14 시 39 분 14 시 40 분 14 시 41 분 14 시 42 분 14 시 43 분 14 시 44 분 14 시 45 분 14 시 46 분 14 시 47 분 14 시 48 분 14 시 49 분 14 시 50 분 14 시 51 분 14 시 52 분 14 시 53 분 14 시 54 분 14 시 55 분 14 시 56 분 14 시 57 분 14 시 58 분 14 시 59 분 15 시 0 분 15 시 1 분 15 시 2 분 15 시 3 분 15 시 4 분 15 시 5 분 15 시 6 분 15 시 7 분 15 시 8 분 15 시 9 분 15 시 10 분 15 시 11 분 15 시 12 분 15 시 13 분 15 시 14 분 15 시 15 분 15 시 16 분 15 시 17 분 15 시 18 분 15 시 19 분 15 시 20 분 15 시 21 분 15 시 22 분 15 시 23 분 15 시 24 분 15 시 25 분 15 시 26 분 15 시 27 분 15 시 28 분 15 시 29 분 15 시 30 분 15 시 31 분 15 시 32 분 15 시 33 분 15 시 34 분 15 시 35 분 15 시 36 분 15 시 37 분 15 시 38 분 15 시 39 분 15 시 40 분 15 시 41 분 15 시 42 분 15 시 43 분 15 시 44 분 15 시 45 분 15 시 46 분 15 시 47 분 15 시 48 분 15 시 49 분 15 시 50 분 15 시 51 분 15 시 52 분 15 시 53 분 15 시 54 분 15 시 55 분 15 시 56 분 15 시 57 분 15 시 58 분 15 시 59 분 16 시 0 분 16 시 1 분 16 시 2 분 16 시 3 분 16 시 4 분 16 시 5 분 16 시 6 분 16 시 7 분 16 시 8 분 16 시 9 분 16 시 10 분 16 시 11 분 16 시 12 분 16 시 13 분 16 시 14 분 16 시 15 분 16 시 16 분 16 시 17 분 16 시 18 분 16 시 19 분 16 시 20 분 16 시 21 분 16 시 22 분 16 시 23 분 16 시 24 분 16 시 25 분 16 시 26 분 16 시 27 분 16 시 28 분 16 시 29 분 16 시 30 분 16 시 31 분 16 시 32 분 16 시 33 분 16 시 34 분 16 시 35 분 16 시 36 분 16 시 37 분 16 시 38 분 16 시 39 분 16 시 40 분 16 시 41 분 16 시 42 분 16 시 43 분 16 시 44 분 16 시 45 분 16 시 46 분 16 시 47 분 16 시 48 분 16 시 49 분 16 시 50 분 16 시 51 분 16 시 52 분 16 시 53 분 16 시 54 분 16 시 55 분 16 시 56 분 16 시 57 분 16 시 58 분 16 시 59 분 17 시 0 분 17 시 1 분 17 시 2 분 17 시 3 분 17 시 4 분 17 시 5 분 17 시 6 분 17 시 7 분 17 시 8 분 17 시 9 분 17 시 10 분 17 시 11 분 17 시 12 분 17 시 13 분 17 시 14 분 17 시 15 분 17 시 16 분 17 시 17 분 17 시 18 분 17 시 19 분 17 시 20 분 17 시 21 분 17 시 22 분 17 시 23 분 17 시 24 분 17 시 25 분 17 시 26 분 17 시 27 분 17 시 28 분 17 시 29 분 17 시 30 분 17 시 31 분 17 시 32 분 17 시 33 분 17 시 34 분 17 시 35 분 17 시 36 분 17 시 37 분 17 시 38 분 17 시 39 분 17 시 40 분 17 시 41 분 17 시 42 분 17 시 43 분 17 시 44 분 17 시 45 분 17 시 46 분 17 시 47 분 17 시 48 분 17 시 49 분 17 시 50 분 17 시 51 분 17 시 52 분 17 시 53 분 17 시 54 분 17 시 55 분 17 시 56 분 17 시 57 분 17 시 58 분 17 시 59 분 18 시 0 분 18 시 1 분 18 시 2 분 18 시 3 분 18 시 4 분 18 시 5 분 18 시 6 분 18 시 7 분 18 시 8 분 18 시 9 분 18 시 10 분 18 시 11 분 18 시 12 분 18 시 13 분 18 시 14 분 18 시 15 분 18 시 16 분 18 시 17 분 18 시 18 분 18 시 19 분 18 시 20 분 18 시 21 분 18 시 22 분 18 시 23 분 18 시 24 분 18 시 25 분 18 시 26 분 18 시 27 분 18 시 28 분 18 시 29 분 18 시 30 분 18 시 31 분 18 시 32 분 18 시 33 분 18 시 34 분 18 시 35 분 18 시 36 분 18 시 37 분 18 시 38 분 18 시 39 분 18 시 40 분 18 시 41 분 18 시 42 분 18 시 43 분 18 시 44 분 18 시 45 분 18 시 46 분 18 시 47 분 18 시 48 분 18 시 49 분 18 시 50 분 18 시 51 분 18 시 52 분 18 시 53 분 18 시 54 분 18 시 55 분 18 시 56 분 18 시 57 분 18 시 58 분 18 시 59 분 19 시 0 분 19 시 1 분 19 시 2 분 19 시 3 분 19 시 4 분 19 시 5 분 19 시 6 분 19 시 7 분 19 시 8 분 19 시 9 분 19 시 10 분 19 시 11 분 19 시 12 분 19 시 13 분 19 시 14 분 19 시 15 분 19 시 16 분 19 시 17 분 19 시 18 분 19 시 19 분 19 시 20 분 19 시 21 분 19 시 22 분 19 시 23 분 19 시 24 분 19 시 25 분 19 시 26 분 19 시 27 분 19 시 28 분 19 시 29 분 19 시 30 분 19 시 31 분 19 시 32 분 19 시 33 분 19 시 34 분 19 시 35 분 19 시 36 분 19 시 37 분 19 시 38 분 19 시 39 분 19 시 40 분 19 시 41 분 19 시 42 분 19 시 43 분 19 시 44 분 19 시 45 분 19 시 46 분 19 시 47 분 19 시 48 분 19 시 49 분 19 시 50 분 19 시 51 분 19 시 52 분 19 시 53 분 19 시 54 분 19 시 55 분 19 시 56 분 19 시 57 분 19 시 58 분 19 시 59 분 20 시 0 분 20 시 1 분 20 시 2 분 20 시 3 분 20 시 4 분 20 시 5 분 20 시 6 분 20 시 7 분 20 시 8 분 20 시 9 분 20 시 10 분 20 시 11 분 20 시 12 분 20 시 13 분 20 시 14 분 20 시 15 분 20 시 16 분 20 시 17 분 20 시 18 분 20 시 19 분 20 시 20 분 20 시 21 분 20 시 22 분 20 시 23 분 20 시 24 분 20 시 25 분 20 시 26 분 20 시 27 분 20 시 28 분 20 시 29 분 20 시 30 분 20 시 31 분 20 시 32 분 20 시 33 분 20 시 34 분 20 시 35 분 20 시 36 분 20 시 37 분 20 시 38 분 20 시 39 분 20 시 40 분 20 시 41 분 20 시 42 분 20 시 43 분 20 시 44 분 20 시 45 분 20 시 46 분 20 시 47 분 20 시 48 분 20 시 49 분 20 시 50 분 20 시 51 분 20 시 52 분 20 시 53 분 20 시 54 분 20 시 55 분 20 시 56 분 20 시 57 분 20 시 58 분 20 시 59 분 21 시 0 분 21 시 1 분 21 시 2 분 21 시 3 분 21 시 4 분 21 시 5 분 21 시 6 분 21 시 7 분 21 시 8 분 21 시 9 분 21 시 10 분 21 시 11 분 21 시 12 분 21 시 13 분 21 시 14 분 21 시 15 분 21 시 16 분 21 시 17 분 21 시 18 분 21 시 19 분 21 시 20 분 21 시 21 분 21 시 22 분 21 시 23 분 21 시 24 분 21 시 25 분 21 시 26 분 21 시 27 분 21 시 28 분 21 시 29 분 21 시 30 분 21 시 31 분 21 시 32 분 21 시 33 분 21 시 34 분 21 시 35 분 21 시 36 분 21 시 37 분 21 시 38 분 21 시 39 분 21 시 40 분 21 시 41 분 21 시 42 분 21 시 43 분 21 시 44 분 21 시 45 분 21 시 46 분 21 시 47 분 21 시 48 분 21 시 49 분 21 시 50 분 21 시 51 분 21 시 52 분 21 시 53 분 21 시 54 분 21 시 55 분 21 시 56 분 21 시 57 분 21 시 58 분 21 시 59 분 22 시 0 분 22 시 1 분 22 시 2 분 22 시 3 분 22 시 4 분 22 시 5 분 22 시 6 분 22 시 7 분 22 시 8 분 22 시 9 분 22 시 10 분 22 시 11 분 22 시 12 분 22 시 13 분 22 시 14 분 22 시 15 분 22 시 16 분 22 시 17 분 22 시 18 분 22 시 19 분 22 시 20 분 22 시 21 분 22 시 22 분 22 시 23 분 22 시 24 분 22 시 25 분 22 시 26 분 22 시 27 분 22 시 28 분 22 시 29 분 22 시 30 분 22 시 31 분 22 시 32 분 22 시 33 분 22 시 34 분 22 시 35 분 22 시 36 분 22 시 37 분 22 시 38 분 22 시 39 분 22 시 40 분 22 시 41 분 22 시 42 분 22 시 43 분 22 시 44 분 22 시 45 분 22 시 46 분 22 시 47 분 22 시 48 분 22 시 49 분 22 시 50 분 22 시 51 분 22 시 52 분 22 시 53 분 22 시 54 분 22 시 55 분 22 시 56 분 22 시 57 분 22 시 58 분 22 시 59 분 23 시 0 분 23 시 1 분 23 시 2 분 23 시 3 분 23 시 4 분 23 시 5 분 23 시 6 분 23 시 7 분 23 시 8 분 23 시 9 분 23 시 10 분 23 시 11 분 23 시 12 분 23 시 13 분 23 시 14 분 23 시 15 분 23 시 16 분 23 시 17 분 23 시 18 분 23 시 19 분 23 시 20 분 23 시 21 분 23 시 22 분 23 시 23 분 23 시 24 분 23 시 25 분 23 시 26 분 23 시 27 분 23 시 28 분 23 시 29 분 23 시 30 분 23 시 31 분 23 시 32 분 23 시 33 분 23 시 34 분 23 시 35 분 23 시 36 분 23 시 37 분 23 시 38 분 23 시 39 분 23 시 40 분 23 시 41 분 23 시 42 분 23 시 43 분 23 시 44 분 23 시 45 분 23 시 46 분 23 시 47 분 23 시 48 분 23 시 49 분 23 시 50 분 23 시 51 분 23 시 52 분 23 시 53 분 23 시 54 분 23 시 55 분 23 시 56 분 23 시 57 분 23 시 58 분 23 시 59 분

In [47]:
for i in range(2,10):
    for j in range(1,10):
        print(i,'x',j,'=', i*j)

2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
3 x 1 = 3
3 x 2 = 6
3 x 3 = 9
3 x 4 = 12
3 x 5 = 15
3 x 6 = 18
3 x 7 = 21
3 x 8 = 24
3 x 9 = 27
4 x 1 = 4
4 x 2 = 8
4 x 3 = 12
4 x 4 = 16
4 x 5 = 20
4 x 6 = 24
4 x 7 = 28
4 x 8 = 32
4 x 9 = 36
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
6 x 1 = 6
6 x 2 = 12
6 x 3 = 18
6 x 4 = 24
6 x 5 = 30
6 x 6 = 36
6 x 7 = 42
6 x 8 = 48
6 x 9 = 54
7 x 1 = 7
7 x 2 = 14
7 x 3 = 21
7 x 4 = 28
7 x 5 = 35
7 x 6 = 42
7 x 7 = 49
7 x 8 = 56
7 x 9 = 63
8 x 1 = 8
8 x 2 = 16
8 x 3 = 24
8 x 4 = 32
8 x 5 = 40
8 x 6 = 48
8 x 7 = 56
8 x 8 = 64
8 x 9 = 72
9 x 1 = 9
9 x 2 = 18
9 x 3 = 27
9 x 4 = 36
9 x 5 = 45
9 x 6 = 54
9 x 7 = 63
9 x 8 = 72
9 x 9 = 81

# 중법 반복문을 사용해서 다중 리스트 출력하기

In [57]:
L1 = []

In [60]:
for i in range(1,6):
    L1.append(list(range(1,6)))

In [61]:
L1

[[1, 2, 3, 4, 5],
 [1, 2, 3, 4, 5],
 [1, 2, 3, 4, 5],
 [1, 2, 3, 4, 5],
 [1, 2, 3, 4, 5],
 [1, 2, 3, 4, 5]]

In [62]:
for item in L1: 
    for i in item:
        print(i)

1
2
3
4
5
1
2
3
4
5
1
2
3
4
5
1
2
3
4
5
1
2
3
4
5
1
2
3
4
5

In [ ]:
# 1. 리스트에 동물 이름이 저장되어있다. for 문을 이용해서 동문 이름의 첫글자만 출력하시오.
# d,c,p

In [78]:
List = ['dog','cat','parrot']

for i in range(len(List)):
    print(List[i][0]," ", end ="")

d  c  p

In [76]:
for item in List:
    print(item[0])

d
c
p

In [ ]:
#2. 리스트에서 세 글자 이상의 문자를 화면에 출력하시오.
# study, python, language

In [85]:
L = ["I", "study", "python", "language", "!"]

for i in L:
    if len(i) >= 3:
        print(i)
    else:
        continue

study
python
language

In [ ]:
#3. 리스트에 저장된 데이터를 아래와 같이 출력하세요.
#apart = [
#        [101, 102], [201, 202], [301, 302]
#        ]
# 101호, 102호, ... 302호

In [89]:
apart = [
       [101, 102], [201, 202], [301, 302]
       ]

for i in apart:
    for j in range(0,2):
        print(i[j],"호")

101 호
102 호
201 호
202 호
301 호
302 호